docs/meedoen/als-designer/community.md
- Slack info direct achter Slack aankondiging
- Design open hour meeting apart met wat extra info
- Gemeente Haarlem en Zandvoort blijkt wel openbaar dus opgenomen in de lijst
- 'Mooi spul' weggelaten
- Rijkshuisstijl als aparte sectie met linkje naar Figma structuur
- Herbruikbare content-footer toegevoegd
=> Paar aanpassingen

docs/project/contact.mdx, src/components/CoreTeam.tsx
Met gebruik van de `svg` bestanden huidskleur en maat van de avatars wat aangepast. Voor Andrea een MVP avatar toegevoegd en voor Peter alleen nog een png. 
⬇
=> docs: update coreteam details

docs/videos/heartbeat.mdx, packages/nlds-design-tokens/src/tokens.json, src/pages/index.tsx
Op basis van de tekst zoals gebruikt voor CX-community een versie van de homepage pitch die duidelijker uitlegt wat een design system (en NL Design System) is.
Van
**Naar**
De lead paragraph is hetzelfde als op de NL Design System banner, de tekst zoals naar de CX community (behalve het aantal deelnemers in de community)
=> docs: improve homepage pitch

docs/footer/colofon.mdx, docs/footer/toegankelijkheidsverklaring.md, footerConfig.js, static/.htaccess
Hoi! Dit is meer “Hidde wil wat meer familiar met de codebase van deze site worden” dan strikt noodzakelijk (dus voel vrij te rejecten), maar zag 'footer' in de URLs van footerlinkjes en heb die eruit gehaald. 
De htaccess voor doorsturen lijkt niets te doen (lokaal niet, maar ook niet in de Vercel preview); is er een go-to manier voor dit soort sites die ik heb gemist?
=> refactor: Tweak URLs of footer links

README.md
Ik merkte dat ik direct na clonen niet gelijk `npm run start` kon doen, de error luidde:
> [ERROR] Error: Cannot find module '@nl-design-system-unstable/nlds-design-tokens/dist/root.css'
Een keertje `npm run build` doen voor de eerste `npm run start` loste dit op,
=> docs: Add extra step before first npm run start

docusaurus.config.js, src/css/custom.css, src/theme/AnnouncementBar/CloseButton/index.tsx, src/theme/AnnouncementBar/CloseButton/styles.module.css, src/theme/AnnouncementBar/Content/index.tsx, src/theme/AnnouncementBar/Content/styles.module.css, src/theme/AnnouncementBar/index.tsx, src/theme/AnnouncementBar/styles.module.css
Dit voegt de in Docusaurus ingebouwde Announcement Bar toe aan de site, met links naar Gebruiker Centraal voor overzicht van de sessies en aanmeldformulier.
**Q: Hoe zit dat er uit?**
**A: zo:**
=> Kondig Design Systems Week aan en link naar aanmeldformulier

docs/project/events/design-systems-week-2023/english/1-program.md, docs/project/events/design-systems-week-2023/english/2-timetable.md
Er stond nog een stukje Nederlandse tekst, die heb ik eruit gehaald.
De link onderin renderde als `div`, heb het `Link` component geïmporteerd om het op te lossen.
=> fix: Remove Dutch text and fix link

docs/project/events/design-systems-week-2023/1-programma.md, docs/project/events/design-systems-week-2023/2-tijdschema-per-dag.md, docs/project/events/design-systems-week-2023/english/1-program.md, docs/project/events/design-systems-week-2023/english/2-timetable.md, docs/project/events/design-systems-week-2023/speakers.json
toegevoegd: 
- de Estonia Design System sessie
gefixed: 
- `<abbr>` tags om 'EN' en 'NL' gezet voor stukje extra toegankelijkheid 
- de `signupLink` prop ingevuld bij alle sessies zodat aanmeld-call-to-actions werken
- op Nederlandse versie miste nog een `import { Link }` waardoor de `<Link>` niet werkte, heb die toegevoegd
=> Voeg Estland toe 🇪🇪

docs/project/events/design-systems-week-2023/1-programma.md, docs/project/events/design-systems-week-2023/2-tijdschema-per-dag.md, docs/project/events/design-systems-week-2023/english/1-program.md, docs/project/events/design-systems-week-2023/english/2-timetable.md, docs/project/events/design-systems-week-2023/speakers.json
Dit voegt Mu-An en Arash toe aan de docs site. 
Dit was eerder onvolledig gedaan in https://github.com/nl-design-system/documentatie/commit/34348d457989e0d899c47a0ea889302b17dae4c0, en daarna ongedaan gemaakt in https://github.com/nl-design-system/documentatie/commit/7d390d5a4095f2a52b95233c141499ab0257a263.
=> Add Mu-An and Arash

docs/project/blijf-op-de-hoogte.mdx, docs/project/events/design-systems-week-2022.mdx, docs/project/events/design-systems-week-2023/english/_category_.json
Ik zag dat we op een paar plekken nog Design System Week zeiden, zonder s, dit maakt 'm consistent.
=> fix: Use consistent name for the week

docs/richtlijnen/formulieren/04-valideer-input.mdx
voegt “Valideer input” toe en die bevat [formulierfouten 17, 18 en 22](https://github.com/nl-design-system/kernteam/issues/256#issuecomment-1740455183)
=> Formulieren: voeg pagina “Valideer input” toe

docs/richtlijnen/formulieren/01-wees-duidelijk.mdx
voegt “Wees duidelijk” toe en die bevat [formulierfouten 1, 13, 15, 21](https://github.com/nl-design-system/kernteam/issues/256#issuecomment-1740455183)
=> Formulieren: voeg pagina “Wees duidelijk” toe

docs/richtlijnen/formulieren/02-vormgeving.mdx
voegt “Vormgeving” toe en die bevat [formulierfouten 5, 9 en 14](https://github.com/nl-design-system/kernteam/issues/256#issuecomment-1740455183) (dit is het tweede menu-item met name opdat we niet twee keer onder elkaar een item hebben dat met “Wees” begint)
=> Formulieren: voeg pagina “Vormgeving” toe

docs/project/events/design-systems-week-2023/1-programma.md, docs/project/events/design-systems-week-2023/2-tijdschema-per-dag.md, docs/project/events/design-systems-week-2023/english/1-program.md, src/components/DSWSession.module.css, src/components/DSWSession.tsx
also fixes `https://https://` typo in one session.
@Yolijn ik vind de videos trouwens _net_ iets mooier staan als ik de naam van de spreker weghaal onder de sessietitel; thoughts? En ik denk dat het goed kan want we noemen die naam vrijwel altijd in de content _en_ altijd in de bio.
=> docs: videos Design Systems Week day 1

docs/project/events/design-systems-week-2023/1-programma.md, docs/project/events/design-systems-week-2023/english/1-program.md
Heb drie signup links weggehaald en één video toegevoegd. Van de andere twee kan Estonia er niet op en moet GOV.UK nog even wachten op de edit (zat iets in dat er nog even uitgeknipt moet).
=> docs: Add videos day 3 and remove signuplinks of past talks

src/components/DSWSession.module.css, src/components/DSWSession.tsx
Video's hadden een vaste breedte waardoor ze op kleine schermen de lay-out stukmaakten, dit lost dat lop.
De `width` en `height` van 100% op de `VimeoPlayer` is wat [de `react-player` docs aanraden](https://www.npmjs.com/package/react-player) (onder “responsive player”) en voorkomt in ieder geval dat dat component vaste afmetingen op het element plaatst.
=> chore: Make videos responsive

blog/2023/20231109-spacing-tokens.md
Typo gefixed (thanks @Rozerinay! <3). En merge van eerdere aanpassing lijkt niet goed te zijn gegaan, die zit hier weer in.
=> fix: Typo in blog post

src/theme/BlogLayout/index.tsx
As somehow the custom Markdown components are not used for the Blogposts I've added `utrecht-html` for now as that component adds utrecht styles directly to the html components.
This solves the issues:
- Spacing of the headings inconsistent, which puts h1 especially close to the breadcrumbs.
- Focus-visible styles inconsistent
=> feat: add utrecht-html to blog

docs/project/events/design-systems-week-2023/1-programma.md, docs/project/events/design-systems-week-2023/english/1-program.md, docs/project/events/heartbeat.mdx, src/components/DSWSession.tsx
(ten behoeve van https://github.com/nl-design-system/kernteam/issues/374)
We were using `VimeoPlayer` from `react-player`, by using `ReactPlayer` we can embed YouTube as well as Vimeo.
In this PR we update the first batch of videos to be served from YouTube instead of Vimeo. 
Will replace more Vimeo embeds with YT embeds in subsequent PR(s) until we have nothing from Vimeo.
Summary:
- rename  `vimeoUrl` prop to `videoUrl` to be more generic
- use `ReactPlayer` instead of `VimeoPlayer` to allow both YouTube and Vimeo at the same time
- update URLs for videos that already exist on YouTube
=> chore: Use generic video player, use YT for some vids

docs/meedoen/als-developer/03-thema-maken.mdx, docs/meedoen/als-developer/05-component-inzetten.mdx, docs/meedoen/design-tokens/README.mdx, docs/project/blijf-op-de-hoogte.mdx, docs/project/events/design-systems-week-2022.mdx, docs/project/events/design-systems-week-2023/1-programma.md, docs/project/events/design-systems-week-2023/english/1-program.md, docs/project/events/heartbeat.mdx, src/components/DSWSession.tsx, src/components/VideoPlayer.module.css, src/components/VideoPlayer.tsx, src/css/custom.css
fixes https://github.com/nl-design-system/kernteam/issues/374
- alles van Design Systems Week 2022 
- alle Heartbeats
- de component inzetten, design tokens vastleggen en design tokens inzetten video's
- VideoPlayer wrapper around `ReactPlayer`: This makes it easier to do accessibility improvements for all videos like turning off keyboard shortcuts (see https://www.200ok.nl/tips/youtube-embed/), use a different player/wrapper and to switch provider should we ever want to do that again.
- styles voor videoplayer (`.video-player` class) verhuisd naar module bij `VideoPlayer` wrapper
=> Replace remaining Vimeo embeds with YouTube embed

docusaurus.config.js
Zoals Robbert zei, hmmm kunnen we die eruit halen?
=> feat: remove reading time from blogposts

blog/2023/20231121-wmebv-gebruikerstesten.md, src/css/custom.css
- blog post over wembv user tests
- de eerste paragraaf een lead grootte gegeven in `custom.css`, vind ik een stuk mooier dan huidig (als eerste stapje; misschien later verder itereren aan blog post styles)
=> feat: add blog post on wembv user tests

src/css/custom.css
Ik zag dat codeblokken in de blog posts geen achtergrondkleur kregen, mogelijk door slordigheid mijnerzijds. Dit lost dat voor nu op.
voor: 
na: 
uit commit message:
> This is ugly, there is likely a more specific place this should go. It is also set on `pre`, but the inline style that the markdown processor sets on one of its containing divs needs the variable to be set already (and targeting that specific div seems potentially more likely to break).
=> fix: geef codeblokken in blog posts weer een achtergrondkleur

lerna.json
https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
This should avoid using up ~250 screenshots from the Argos budget for every PR merge.
=> ci: avoid build for release with `skip ci`

packages/nlds-design-tokens/src/tokens.json, src/components/Bingo.tsx, src/components/CodeBlockSyntaxHiglighting.tsx, src/theme/MDXComponents/Pre.tsx, test/visual/argos-visual-regression.test.ts
Added a new feature to the visual regression test runner: pages that contain `<meta name="argos" content="false">` are skipped. The bingo page will now be skipped, because the randomized content caused the test to (practically) always fail.
The code examples using three backticks from `.md` files are now highlighted using a new component: `CodeBlockSyntaxHighlighting`, which extends the Utrecht `CodeBlock`.
=> feat: add `CodeBlockSyntaxHighlighting` component

package.json, pnpm-lock.yaml, src/_generate-component-pages/index.ts, src/components/Canvas/Canvas.tsx, src/components/CodeBlockSyntaxHighlighting.tsx, src/components/examples/GraffitiForm.tsx, src/theme/MDXComponents/Pre.tsx, src/theme/SearchBar/index.tsx
This doesn't work yet, because Prettier switched to an asynchronous API with `await` and that doesn't play well with server side formatting of code snippets yet.
=> build: update to Prettier 3

docs/richtlijnen/formulieren/05-voorspelbaar.mdx, src/components/Canvas/Canvas.tsx
=> docs: make example canvas optional

docs/richtlijnen/formulieren/00-alle-richtlijnen/_visual-design-field-contrast-code.mdx, docs/richtlijnen/formulieren/00-alle-richtlijnen/_visual-design-placeholder-contrast-code.mdx, docs/richtlijnen/formulieren/00-alle-richtlijnen/_visual-design-text-contrast-code.mdx, package.json, packages/nlds-design-tokens/src/tokens.json, pnpm-lock.yaml, src/components/Canvas/Canvas.module.css, src/components/Canvas/Canvas.tsx, src/components/ContrastRatio.module.css, src/components/ContrastRatio.tsx, src/components/FormFieldTextbox.tsx, src/components/Guideline.module.css, src/components/Guideline.tsx, src/pages/contrast/index.module.css, src/pages/contrast/index.tsx
We kunnen deze pagina gebruiken om te linken naar een contrastberekening, in plaats van linken naar contrast-ratio.com omdat daar nu reclame staat.
Dan wordt de URL bijvoorbeeld: https://nldesignsystem.nl/contrast/?background-color=%23ffffff&color=%23606060
=> feat: add contrast checker page

docs/richtlijnen/formulieren/00-alle-richtlijnen/_errors-feedback.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_errors-location.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_errors-no-native.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_errors-summary-code.mdx, docs/richtlijnen/formulieren/00-alle-richtlijnen/_errors-summary.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_errors-timing.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/errors.mdx
We hadden in #538 nog een aantal issues gemist dus die heb ik hier nog gefixed. 
Eén ding is niet rechttoerechtaan fix, nl dat ik ook `role=alert` heb weggehaald van de samenvatting + opsomming met fouten, en de aanbeveling heb toegevoegd die focus te geven (ipv `role=alert`). Discussie daarover [hadden we in Slack](https://codefornl.slack.com/archives/C02CWGL2M18/p1706272632252879), mochten we daar nog over willen doorpraten kan ik die wijziging ook nog even uit deze PR halen.
=> Fix foutmeldingen feedback

src/components/CardGroup.module.css, src/components/HomepageHero.module.css, src/css/custom.css
Dit fixt twee dingen: 
- evenveel spacing boven en onderin het paarse blok (opgemerkt door en gecheckt met @jeffreylauwers), dit was wsl eerder geen issue door de schuine lijn die we hadden
- de horizontale scroll op mobiel (fixes https://github.com/nl-design-system/documentatie/issues/577); met meerdere dingen:
-  er waren meer linkjes in de footer naast elkaar stonden dan in de ~`550px` pastte die we als triggerpunt gebruikten om van verticaal naar horizontaal te gaan 
- de media query voor cards werd op mobiel en sommige schermen anders geïnterpreteerd dan we wilden, heb de logica omgedraaid zodat er pas twee kolommen worden getriggerd vanaf een zekere breedte ipv tot een zekere breedte niet getriggered, en daarnaast `minmax(0, 1fr)` gebruikt ipv `1fr` zodat de kolommen niet uit hun …
=> Fix design bugs

docs/richtlijnen/formulieren/00-alle-richtlijnen/_button-accessible-name.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_button-disabled.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_button-placement.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_button-text.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_confirmation-success.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_description-placement.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_errors-clarity.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_errors-no-native.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_errors-timing.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_help-allow-copy-paste.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_label-above-field.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_label-always-visible.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/_placeholder-clarity.md, docs/richtlijnen/formulieren/00-alle-richtlijnen/multistep.mdx
Aan alle Engelstalige linkteksten lang="en" toegevoegd.
In markdown wordt het dan bijvoorbeeld voor een link:
```
[<span lang="en">Accessible SVGs: Perfect Patterns For Screen Reader Users</span>](https://www.smashingmagazine.com/2021/05/accessible-svg-patterns-comparison/)
```
en `<span lang="en">Accessible SVGs: Perfect Patterns For Screen Reader Users</span>` voor teksten.
Issue: https://github.com/nl-design-system/documentatie/issues/583
=> docs: add lang=en to english text

static/.htaccess
URLs like https://nldesignsystem.nl/richtlijnen/formulieren/alle-richtlijnen/foutmeldingen/ are currently broken because we removed the `alle-richtlijnen` bit, this tries to send people to the same page without the `alle-richtlijnen` prefix, which should exist for all cases.
=> fix: add redirect from old “alle richtlijnen” pages

docs/richtlijnen/tekst-en-taalgebruik/tekst-en-taalgebruik.md
Ter beoordeling of we op de goede weg zijn.
URL: https://documentatie-git-feedback-renate-nl-design-system.vercel.app/richtlijnen/tekst-en-taalgebruik/
Ter vergelijking met de oude versie:
https://nldesignsystem.nl/richtlijnen/tekst-en-taalgebruik/
Introductie is uitgebreider gemaakt, wat niet tot de richtlijnen hoort, valt onder de H2 introductie nu.
En we hebben duidelijker aangegeven wat de richtlijnen zijn door de tekst van het h2 kopjes aan te passen naar:
- [Schrijf leesbare teksten](https://documentatie-git-feedback-renate-nl-design-system.vercel.app/richtlijnen/tekst-en-taalgebruik/#schrijf-leesbare-teksten)
- [Zorg voor correcte en consistente grammatica](https://documentatie-git-feedback-renate-nl-design-system.vercel.app/richtlijnen/tekst-en-taalgebruik/#zorg-voor-correcte-en-co …
=> guidelines: draft voorstel nieuwe conten en structuur tekst en taalgebruik

.github/workflows/cd.yml
Bump `pnpm/action-setup` to the latest version, make sure the pnpm cache is used.
Make version numbers of all actions explicit.
=> build: use pnpm cache

docs/richtlijnen/formulieren/_help-show-required.md
- 'Optioneel' vervangen voor 'Niet verplicht'. Want 'Optioneel' is niet B1. Zie ook feedback Rozerin https://github.com/nl-design-system/documentatie/discussions/473#discussioncomment-7965420.
- Enkele aanhalingstekens in plaats van dubbele. En deze daarna ook toegepast bij opvolgende regel.
- Opsomming qua tekst verder gelijk getrokken.
- Asterisk voorafgaand aan * en daarna 'sterretje' vervangen voor het woord 'asterisk'.
=> Tekst update voor help-show-required

blog/2024/20240311-gebruikerstest-ondernemers.md
we were linking to the end of the presentation, this fixes it to be the start of the presentation
=> docs: improve timestamp

docs/wcag/1.1.1.mdx
WCAG-pagina 1.1.1 Niet-tekstuele content: Aanpassing tekst nav issue [#692](https://github.com/nl-design-system/documentatie/issues/692)
URL: https://documentatie-git-wgac-1-1-1-additions-nl-design-system.vercel.app/wcag/1.1.1
=> WCAG-pagina 1.1.1 Niet-tekstuele content: Aanpassing tekst nav issue 692

compose.yaml, static/.htaccess
Temporarily redirect to /factsheets/managers
Also add a volume mount for `./static/factsheets` to the Docker file
=> chore: redirect /factsheets

docs/handboek/developer/03-thema-maken.mdx, docusaurus.config.ts
Extra uitleg gebaseerd op [eerder geschreven blogpost-samenvatting van token-onboarding door Robbert](https://github.com/nl-design-system/documentatie/blob/95aec422bceb7db15d0fcbdbf1ac346dee7e9853/blog/2023-08-17-themen.md), en video's op een zo logisch mogelijke manier ingeleid (de eerste door een kop en de tweede met een extra zin ertussen).
Dit alles fixes https://github.com/nl-design-system/documentatie/issues/499.
De `title` bij de code blocks wordt niet weergegeven, los issue daarvoor (https://github.com/nl-design-system/documentatie/issues/580) kan later worden opgepakt.
=> Update “Thema maken” pagina met meer uitleg

docs/project/faq.mdx, sidebarConfig.ts
Context: deze fixes https://github.com/nl-design-system/kernteam/issues/597 in de [Mediakit v1 milestone](https://github.com/nl-design-system/kernteam/milestone/66).
[PREVIEW van FAQ pagina](https://documentatie-git-add-faq-nl-design-system.vercel.app/project/faq)
Hiermee voegen we de FAQ ook toe als FAQ. Antwoorden proberen zoveel mogelijk formuleringen te gebruiken als op elders op de site, maar worden soms door de vraag naar een net iets andere formulering gedwongen (feature, geen bug).
@Robbert de [laatste vraag over security](https://documentatie-git-add-faq-nl-design-system.vercel.app/project/faq#hoe-is-security-geregeld-binnen-nlds) is nieuw en hebben we nog niet eerder gecheckt, wil je kritisch kijken naar of het antwoord klopt en goede voorbeelden geeft van wat we nu doen qua …
=> Voeg FAQ toe als FAQ pagina

docs/project/faq.mdx
Link to "Waarom maken jullie niet gewoon zelf componenten en patronen?" was incorrect, and the title was inconsistent.
=> TOC link fix

docs/wcag/1.1.1.mdx, docs/wcag/1.3.5.mdx, docs/wcag/2.1.1.mdx, docs/wcag/3.3.1.mdx, docs/wcag/3.3.3.mdx, docs/wcag/3.3.4.mdx, docs/wcag/4.1.3.mdx
Related issue: https://github.com/nl-design-system/documentatie/issues/753
URLs:
- https://documentatie-git-wcag-add-link-to-quickref-nl-design-system.vercel.app/wcag/1.1.1
- https://documentatie-git-wcag-add-link-to-quickref-nl-design-system.vercel.app/wcag/1.3.5
- https://documentatie-git-wcag-add-link-to-quickref-nl-design-system.vercel.app/wcag/2.1.1
- https://documentatie-git-wcag-add-link-to-quickref-nl-design-system.vercel.app/wcag/3.3.1
- https://documentatie-git-wcag-add-link-to-quickref-nl-design-system.vercel.app/wcag/3.3.3
- https://documentatie-git-wcag-add-link-to-quickref-nl-design-system.vercel.app/wcag/3.3.4
- https://documentatie-git-wcag-add-link-to-quickref-nl-design-system.vercel.app/wcag/4.1.3
=> WCAG-pagina's: Voeg link naar succescriterium binnen de WCAG Quickref pagina toe

docs/handboek/developer/03-thema-maken.mdx, docs/handboek/introductie.md
fixes https://github.com/nl-design-system/kernteam/issues/598 
Paar verduidelijkingen: 
- meer gericht op professional die straks misschien aan de slag gaat met code of design en wil begrijpen hoe het concreet werkt; minder op voordelen
- linkjes toegevoegd en gefixt
- uitleg estafettemodel compacter gemaakt met verwijzing naar estafettemodelpagina en definition of done
=> Verduidelijk introductiepagina

docs/richtlijnen/formulieren/_form_footer_info.md, docs/richtlijnen/stijl/_style_footer_info.md, docs/richtlijnen/stijl/iconen.md, docs/richtlijnen/stijl/kleuren.md, docs/richtlijnen/stijl/ruimte.md, docs/richtlijnen/stijl/typografie.md
Related issue: https://github.com/nl-design-system/documentatie/issues/751
URL: https://documentatie-git-guidelines-add-beta-st-693ace-nl-design-system.vercel.app/richtlijnen/introductie
Voor de stijl-pagina's heb ik de tekst in de pagina's zelf gezet, in plaats van een include gemaakt. Dit is even een quick fix, omdat deze pagina's toch qua indeling op de schop gaan.
=> Richtlijnen: op elke pagina duidelijk vermelden dat de richtlijnen nog in beta zijn.

docs/richtlijnen/formulieren/_errors-feedback.md
Issue: https://github.com/nl-design-system/documentatie/issues/809
URL: https://documentatie-git-guidelines-example-sam-f58e10-nl-design-system.vercel.app/richtlijnen/formulieren/foutmeldingen#update-het-title-element-in-de-head
=> Richtlijnen: Voorbeeld title bij foutmeldingen gelijktrekken met Figma voorbeeld

.gitignore, packages/nlds-design-tokens/src/tokens.json, src/components/SessionTable.tsx, src/css/custom.css, src/theme/BlogPostItems/index.tsx, src/theme/Navbar/MobileSidebar/Toggle/index.tsx
Een aantal a11y fixes alvast.
Solves
- https://github.com/nl-design-system/documentatie/issues/410
- https://github.com/nl-design-system/documentatie/issues/408
- Default voor `--nlds-sidebar-menu-item-active-border-color` is nu white. Omdat de sidenav css gedeeld wordt met de desktop sidenav heb `--nlds-sidebar-menu-item-active-border-color: #148839;` toegevoegd aan een bestaande breakpoint theme overwrite. Ik zou liever de CSS voor de `menu_link` op deze breakpoint aanpassen zodat er een mobile token kan zijn maar dit is meer in lijn met de bestaande CSS aanpak.
- https://github.com/nl-design-system/documentatie/issues/589
- https://github.com/nl-design-system/documentatie/issues/417
=> fix: accessibility issues website

vercel.json
Pushes to the assets branch should not trigger a Vercel deploy
See https://vercel.com/docs/projects/project-configuration/git-configuration#git.deploymentenabled
=> build: skip Vercel for `assets` branch

src/_generate-component-pages/index.ts
When generating component pages, hardcode Utrecht for now. The components "select" and "blockquote" are still broken but this should be fixed once they're added to the themes repository again.
=> fix: make component examples work once more

.github/workflows/cd.yml
New pushes to a branch should cancel a running build as that is no longer relevant.
=> build: cancel workflows for new pushes

vercel.json
Make sure that Vercel does not trigger builds for Dependabot PRs.
When the "ignoreCommand" exits with 0, the build is ignored. When it exits with 1, the build continues.
=> build: make Vercel ignore Dependabot

docs/wcag/0-introduction.mdx, docs/wcag/1.1.1.mdx, docs/wcag/1.3.1.mdx, docs/wcag/1.3.5.mdx, docs/wcag/2.1.1.mdx, docs/wcag/2.4.13.mdx, docs/wcag/2.4.7.mdx, docs/wcag/3.2.1.mdx, docs/wcag/3.2.2.mdx, docs/wcag/3.3.1.mdx, docs/wcag/3.3.3.mdx, docs/wcag/3.3.4.mdx, docs/wcag/4.1.3.mdx
Related issue: #848 
URL: https://documentatie-git-wcag-uitleg-nl-design-system.vercel.app/wcag/introduction.
De Introductiepagina wordt nog uitgebreid met met info over de status van de uitleg, zie issue #892
=> WCAG-pagina's: het kopje "Korte samenvatting" wordt "Uitleg".

docs/richtlijnen/formulieren/_errors-no-native.md
URL: https://documentatie-git-guidelines-errors-prog-16038b-nl-design-system.vercel.app/richtlijnen/formulieren/foutmeldingen#gebruik-geen-html-formuliervalidatie
Deze PR komt voort uit de discussie bij het issue over de blogpost over foutmeldingen:
https://github.com/nl-design-system/documentatie/issues/613#issuecomment-1943450280
Robbert:
> Ik zou graag wel duidelijk maken dat het required attribuut niet verboden is voor websites die geen JavaScript gebruiken om het formulier te valideren.
Ik denk dat deze info toevoegen aan de richtlijn duidelijker en makkelijker vindbaar is dan het toevoegen aan een blogpost.
=> Richtlijnen: Voeg fallback voor progressive enhancement toe aan RL HTML-validatie

docs/wcag/1.1.1.mdx, docs/wcag/1.3.1.mdx, docs/wcag/1.3.5.mdx, docs/wcag/2.1.1.mdx, docs/wcag/2.4.13.mdx, docs/wcag/2.4.2.mdx, docs/wcag/2.4.4.mdx, docs/wcag/2.4.7.mdx, docs/wcag/3.2.1.mdx, docs/wcag/3.2.2.mdx, docs/wcag/3.3.1.mdx, docs/wcag/3.3.3.mdx, docs/wcag/3.3.4.mdx, docs/wcag/4.1.3.mdx
In de titels van de WCAG-pagina's staat
`WCAG Succescriterium`
En bij links gebruiken we
`WCAG-succescriterium`
Deze PR trekt dit gelijk  door het streepje ook in de titles op te nemen.
=> WCAG-pagina's: WCAG Succescriterium veranderen in WCAG-succescriterium

.github/workflows/cd.yml, package.json, pnpm-lock.yaml
- update package.json
- update "engines"
- update "packageManager" to the full corepack supoorted hash
- remove "version" input in workflow jobs so that "pnpm/action-setup" uses the pnpm version provided by "packageManager" in `package.json`
- udpate pnpm-lock.yaml
An environment variable "ENABLE_EXPERIMENTAL_COREPACK" was added to the build environment on Vercel. This makes sure that Vercel will use corepack which will ensure the correct version of pnpm is used.
=> build: bump pnpm to v9

static/.htaccess
only `/events` and `/events/` now link to `/community/events/overzicht`
=> fix: 301 redirect

docs/richtlijnen/formulieren/_button-accessible-name.md, docs/richtlijnen/formulieren/_label-accessible-name.md, docs/richtlijnen/formulieren/_when-which-compat.md, docs/wcag/0-introduction.mdx
Preview: https://documentatie-git-wcag-missing-link-nl-design-system.vercel.app/wcag/introduction
=> WCAG-pagina's: Voegt missende links op de intropagina toe en fixt inconsistentie in naamgeving 4.1.2

.github/workflows/cd.yml
Update GitHub actions to their latest versions. Use commit hashes instead of tags to prevent tampering. The tag is still added as a comment.
Dependabot supports this notation and will create pull requests using the exact same notation.
Add `--frozen-lockfile` to `pnpm install` to make it explicit that this is how `pnpm install` runs in CI.
Turn `run:` jobs that only run one command-line program into oneliners to slightly improve readability.
=> build: update GitHub actions

src/components/NewsletterSignUp.tsx
For some reason geeft de La Posta server een error als de 7e checkbox `value=7` heeft, dit getal overslaan fixt het issue.
=> Fix La Posta form submit

docs/footer/colofon.mdx, docs/open-source/cc0.md, docs/open-source/eupl.md
Op de [Colofon pagina](https://documentatie-git-docs-licenses-nl-design-system.vercel.app/colofon) heb ik links naar de nieuwe [EUPL](https://documentatie-git-docs-licenses-nl-design-system.vercel.app/open-source/eupl) en [CC0](https://documentatie-git-docs-licenses-nl-design-system.vercel.app/open-source/cc0) pagina's toegevoegd.
Onderin de licentiepagina's staat wat uitleg in een `<aside>`, die zou ik later graag naar boven verplaatsen met een beter design van een "Spotlight section" component — maar daarvoor zijn nog geen tokens gekozen.
=> docs: add open source licenses we use

.github/workflows/cd.yml
Use GitHub's own actions to deploy the site to GitHub Pages.
=> build: use actions/deploy-pages for GH Pages

docs/wcag/0-introduction.mdx, docs/wcag/3.1.1.mdx, docs/wcag/3.1.2.mdx
Related issue: https://github.com/nl-design-system/documentatie/issues/666
Preview: https://documentatie-git-wcag-3-1-2-taal-van-on-2c10af-nl-design-system.vercel.app/wcag/3.1.2
=> WCAG-pagina: 3.1.2 Taal van onderdelen

src/css/custom.css
Zowel https://nldesignsystem.nl/handboek/help-wanted-stappenplan als https://nldesignsystem.nl/richtlijnen/formulieren/autocomplete deden het niet goed op tablet-size en mobile-size. Een snelle fix die later mooier kan als we ontswizzled zijn.
=> fix: mvp mobile-viewport

docs/handboek/designer/README.md, docs/handboek/designer/voorbeeld-thema.md
Ik kreeg een melding bij `build` dat er twee linkjes dood waren.
=> fix: links to stijl richtlijnen

docs/componenten/_icon.md, docs/project/faq.mdx, docs/project/over-nl-design-system.mdx, docs/richtlijnen/formulieren/_autocomplete-value.md, docs/richtlijnen/formulieren/_help-show-required-intro.md, docs/richtlijnen/formulieren/_link-in-new-tab.md, docs/richtlijnen/formulieren/_when-which-compat.md, docs/wcag/0-introduction.mdx, docs/wcag/1.1.1.mdx, docs/wcag/1.3.1.mdx, docs/wcag/1.3.5.mdx, docs/wcag/2.1.1.mdx, docs/wcag/2.4.10.mdx, docs/wcag/2.4.13.mdx, docs/wcag/2.4.2.mdx, docs/wcag/2.4.4.mdx, docs/wcag/2.4.7.mdx, docs/wcag/3.1.1.mdx, docs/wcag/3.1.2.mdx, docs/wcag/3.2.1.mdx, docs/wcag/3.2.2.mdx, docs/wcag/3.3.1.mdx, docs/wcag/3.3.3.mdx, docs/wcag/3.3.4.mdx, docs/wcag/4.1.2.mdx, docs/wcag/4.1.3.mdx
In alle pagina's binnen docs.
Behalve parsing, want die vervalt in 2.2
Issue: https://github.com/nl-design-system/documentatie/issues/811
Preview: https://documentatie-git-wcag-link-wcag-2-2-nl-nl-design-system.vercel.app/richtlijnen
=> WCAG-pagina's: update links naar Nederlandse tekst WCAG naar versie 2.2

docs/wcag/0-introduction.mdx, docs/wcag/2.4.1.mdx
Gerelateerd issue: #654
Preview https://documentatie-git-wcag-2-4-1-blokken-omzeilen-nl-design-system.vercel.app/wcag/2.4.1
@Robbert ik zie vaak dat skiplinks en andere interne links fout gaan als ze in JavaScript zijn gemaakt.
Ik heb wat zitten testen in de code https://codepen.io/rianrietveld/pen/oNRYEpJ, zodat het werkt in vanilla JS maar heb geen idee of dit iets is om te delen. Vooral de volgorde is belangrijk, eerst tabindex zetten en dan pas scrollen
=> WCAG-pagina: 2.4.1 Blokken omzeilen

.github/dependabot.yml
day, time, and timezone don't work with monthly schedule
=> build: fix dependabot schedule

docs/handboek/organisatie/meedoen.md
Omdat ik bezig was 'm in slides mee te nemen, heb ik gelijk geprobeerd deze pagina wat te verbeteren en consistenter te maken:
- af en toe herschreven om eenvoudiger / leesbaarder te maken,
- opsommingen die eindigen op een `.`, headings zonder `:` 
- Storybook consequent met hoofdletter
- links die alleen de URL waren zo aangepast dat het een logische linknaam heeft
Inhoudelijk begrijp ik de uitleg bij Niveau 2: Richtlijnen gebruiken, het is niet zo bewijsbaar als aanwezigheid van informatie op specifieke plekken. Maar het is wel na te gaan of er toegepast of uitgelegd is, mijn voorstel is dat op te nemen. Strenger dan dat niet logisch nu we nog geen geversioneerde richtlijnen hebben.
=> docs: Tweak meedoen als organisatie / niveaus

docs/richtlijnen/formulieren/README.mdx
Voegt link naar [blogpost over foutmeldingen](https://nldesignsystem.nl/blog/toegankelijke-foutmeldingen-formulieren) op de intro-pagina van de formulierrichtlijnen.
Preview: https://documentatie-git-crosslinken-blogposts-f779d1-nl-design-system.vercel.app/richtlijnen/formulieren/
=> Richtlijnen: Link naar blogpost over foutmeldingen op de intro-pagina van de formulierrichtlijnen

docs/componenten/unordered-list/index.mdx
Johan Groenen merkte op in Slack:
> Ik zag dat "Unordered list" een afbeelding heeft van een ordered list, en dat de link erbij verwijst naar "Tooltip"
=> fix: correct backlog link and illustration for Unordered list

docs/componenten/table/index.mdx
Blijkbaar stond er informatie over de Paragraph in de Table documentatie. Ik heb dit veranderd naar Table.
Het issueNumber moet alleen nog worden toegewezen.
=> Description en title Table toegevoegd

docs/componenten/skip-link/index.mdx, docs/wcag/2.4.1.mdx, docs/wcag/2.4.13.mdx, docs/wcag/2.4.7.mdx
Gerelateerd issue: #1064 
Preview: https://documentatie-git-wcag-skiplink-correction-nl-design-system.vercel.app/wcag/2.4.1
Ook een typo in de componentdescription over skiplinks aangepast en interne links naar deze wecag pagina toegevoegd.
=> WCAG: Wanneer te testen voor skiplinks aangepast

src/css/custom.css
This used to be part of `utrecht-document`, but it appears to have been removed — accidentally?
=> style: disable incorrect font-smoothing from Docusaurus

docs/handboek/component-bijdragen/candidate-stappenplan.mdx
De stap 'Community' vindt eerder plaats dan 'Candidate'. Daarom heb ik de volgorde aangepast.
=> Volgorde Candidate item in sidebar gewijzigd

src/css/custom.css
(checkboxes on forms were stretched vertically because they were part of a flex context, this keeps them their original ratio, by removing their participation from the flex context)
with this PR, this is what the component filter checkboxes look like:
and this is what the sign up form checkboxes look like:
=> Make checkboxes across sign up forms and component filter consistent

src/components/ComponentPage.tsx, src/components/InlineHeadingGroup.module.css, src/components/InlineHeadingGroup.tsx
refactor:
```html
<h1>Accordion <span>Todo</span></h1>
```
to:
```html
<hgroup>
<h1>Accordion</h1>
<p> <span>Todo</span></p>
</hgroup>
```
=> refactor: move badge out of h1 of component page

docs/community/events/design-open-hour/aanmelden.mdx, docs/community/events/design-open-hour/design-open-hour.mdx, docs/community/events/developer-open-hour/aanmelden-success.mdx, docs/community/events/developer-open-hour/aanmelden.mdx, docs/community/events/developer-open-hour/developer-open-hour.mdx, sidebarConfig.ts
Deze PR voegt één nieuwe pagina toe: 
- [Developer Open Hour](https://documentatie-git-add-dev-open-hour-nl-design-system.vercel.app/events/developer-open-hour) met [subpagina voor aanmelden](https://documentatie-git-add-dev-open-hour-nl-design-system.vercel.app/events/developer-open-hour/aanmelden)
Deze PR wijzigt één pagina: 
- [Design Open Hour](https://documentatie-git-add-dev-open-hour-nl-design-system.vercel.app/events/design-open-hour): refereert nu aan Slack, legt uit hoe je op Slack komt, spreekt niet meer van toevoegen aan calender invites
=> Voeg developer open hour toe en tweak die van designers

docs/wcag/2.4.1.mdx
Gerelateerd issue: #1065
Preview: https://documentatie-git-wcag-skiplink-placement-nl-design-system.vercel.app/wcag/2.4.1
=> WCAG-pagina's: Verduidelijking of een skiplink binnen of buiten de header kan staan

docs/richtlijnen/formulieren/button/README.mdx, docs/richtlijnen/formulieren/confirmation/README.mdx, docs/richtlijnen/formulieren/description/README.mdx, docs/richtlijnen/formulieren/error/3-clarity/README.mdx, docs/richtlijnen/formulieren/help/README.mdx, docs/richtlijnen/formulieren/keyboard-behaviour/README.mdx, docs/richtlijnen/formulieren/label/2-visible-acccessible-name/README.mdx, docs/richtlijnen/formulieren/link/README.mdx, docs/richtlijnen/formulieren/multistep/README.mdx, docs/richtlijnen/formulieren/placeholder/README.mdx, docs/richtlijnen/formulieren/questions/README.mdx, docs/richtlijnen/formulieren/visual-design/4-focus-visible/README.mdx, docs/richtlijnen/formulieren/when-which/README.mdx
Ik denk dat het op de overview pages voor formulier richtlijnen niet logisch is dat we ook nog een table-of-contents hebben rechts. Mijn voorstel is dus om deze uit te zetten.
=> docs: remove sidebar from form overview pages

lint-staged.config.cjs
Make sure eslint and npm-pkg-json-lint still work if files that are commit are ignored by .eslintignore or .npmpkgjsonlintignore
=> fix: lint-staged

.changeset/wcag-1.4.8-summary.md, docs/componenten/paragraph/_guidelines.md, docs/richtlijnen/stijl/ruimte.md, docs/richtlijnen/stijl/typografie.md, docs/wcag/0-introduction.mdx, docs/wcag/1.4.08.mdx, docs/wcag/summaries/_1.4.8-summary.md, src/theme/DocSidebarItem/Category/index.tsx
Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/1304
Preview: https://documentatie-git-wcag-summary-148-visua-69b6d6-nl-design-system.vercel.app/wcag/1.4.8
@hidde:
Dit is een samenvatting voor niet technische personen, meer het 'wat' en 'waarom'.
Pas bij de volledige uitleg kom precies het 'hoe'.
=> WCAG-pagina's: Summary 1.4.8 Visuele weergave

.changeset/wcag-1.2.6-changelog.md, docs/wcag/0-introduction.mdx, docs/wcag/1.2.06.mdx, docs/wcag/summaries/_1.2.6-summary.md
Issue: https://github.com/nl-design-system/documentatie/issues/1304
Preview: https://documentatie-git-wcag-126-gebarentaal-summary-nl-design-system.vercel.app/wcag/1.2.6
Dit is een samenvatting voor niet technische personen, meer het 'wat' en 'waarom'.
Pas bij de volledige uitleg kom precies het 'hoe'.
=> WCAG-pagina's: 1.2.6 Gebarentaal (vooraf opgenomen) summary

.changeset/wcag-2.5.5-summary.md, docs/wcag/0-introduction.mdx, docs/wcag/2.5.05.mdx, docs/wcag/summaries/_2.5.5-summary.md
Issue:  #1304
Preview: https://documentatie-git-wcag-255-target-size-summary-nl-design-system.vercel.app/wcag/2.5.5
Dit is een samenvatting voor niet technische personen, meer het 'wat' en 'waarom'.
Pas bij de volledige uitleg kom precies het 'hoe'.
=> WCAG-pagina's: 2.5.5 Grootte van het aanwijsgebied (uitgebreid) summary

.changeset/docs-fix-broken-links-changelog.md, docs/richtlijnen/formulieren/_form_footer_info.md, docs/voorbeelden/patronen/formulieren/_pattern_footer_info.mdx, docs/voorbeelden/patronen/formulieren/controlepagina.mdx, docs/voorbeelden/patronen/formulieren/funnel-header.mdx, docs/voorbeelden/patronen/formulieren/inloggen.mdx, docs/voorbeelden/patronen/formulieren/intropagina.mdx, docs/voorbeelden/patronen/formulieren/niet-verplichte-velden.mdx, docs/voorbeelden/patronen/formulieren/terug-navigeren.mdx, docs/voorbeelden/patronen/formulieren/uploaden.mdx, docs/voorbeelden/patronen/formulieren/volgende-stap.mdx, docs/voorbeelden/patronen/formulieren/voortgang-indicatie.mdx
Deze PR fixt wat gebroken links na de refactoring van de richtlijnen
=> docs: fix broken links and typos

docs/richtlijnen/formulieren/status/1-screenreaders/README.mdx, docs/richtlijnen/formulieren/status/1-screenreaders/_category_.json, docs/richtlijnen/formulieren/status/1-screenreaders/_code.mdx, docs/richtlijnen/formulieren/status/1-screenreaders/_guideline.md, docs/richtlijnen/formulieren/status/2-zoomed-in/README.mdx, docs/richtlijnen/formulieren/status/2-zoomed-in/_category_.json, docs/richtlijnen/formulieren/status/2-zoomed-in/_guideline.md, docs/richtlijnen/formulieren/status/3-enough-time/README.mdx, docs/richtlijnen/formulieren/status/3-enough-time/_category_.json, docs/richtlijnen/formulieren/status/3-enough-time/_guideline.md, docs/richtlijnen/formulieren/status/README.mdx, docs/richtlijnen/formulieren/status/_category_.json, docs/wcag/4.1.03.mdx
Review: https://documentatie-git-docs-add-status-update-48e113-nl-design-system.vercel.app/richtlijnen/formulieren/status/
fixes #1290 
fixes #1291 
fixes #1292
fixes #1293
Notities:
- let op, dit is nog niet de volledige 'status' sectie'; we gaan komende weken in https://github.com/nl-design-system/documentatie/issues/1289 meer content toevoegen over statussen; wmb kan deze al gemerged worden voor de rest er is
- ik gebruik steeds 'statusberichten' ipv 'statusmeldingen' wat we eerder gebruikten om in lijn te blijven met den officiële 2.2 vertaling
- ik heb m'n best gedaan het onderscheid tussen 'verandering van content' en 'verandering van context' impliciet te maken, door het te hebben over 'veranderingen binnen een pagina'
=> Voeg richtlijnen over status toe

docs/community/events/design-systems-week-2024/programma.md, src/components/DSWSession.tsx
Nieuwe props:
- `captioned` op `DSWSession` die aangeeft of de sessie schrijftolk heeft
Andere nieuwigheid:
- zinnetje dat op basis van `captioned` zegt dat er een schrijftolk aanwezig is.
=> Laat zien of er een schrijftolk aanwezig is

.changeset/guidelines-no-input-mask.md, docs/richtlijnen/formulieren/help/8-avoid-input-mask/README.mdx, docs/richtlijnen/formulieren/help/8-avoid-input-mask/_category_.json, docs/richtlijnen/formulieren/help/8-avoid-input-mask/_guideline.md, docs/richtlijnen/formulieren/help/8-avoid-input-mask/_guideline.mdx
Issue: https://github.com/nl-design-system/documentatie/issues/758
Preview: https://documentatie-git-guideline-no-mask-in-input-nl-design-system.vercel.app/richtlijnen/formulieren/voorkom-fouten/geen-invoerpatronen
=> Richtlijn bij Voorkom fouten: Gebruik geen invoerpatroon op een formulierveld.

src/components/ComponentOverview.tsx, src/components/ComponentPage.tsx
Door de filter keuzes naar de search parameters in de url te pushen blijven de filters aan na refresh én kan een URL inclusief filters worden gedeeld.
Stel je gaat nu naar https://www.nldesignsystem.nl/componenten/?filter=helpWanted&filter=todo dan doet het niets.
Met deze PR kun je naar https://documentatie-git-fix-component-implemen-9870e6-nl-design-system.vercel.app/componenten/?filter=helpWanted&filter=todo en dan zie je geen componenten meer met Help Wanted of Todo status.
=> feat: use search params for filters

docs/wcag/2.2.04.mdx
was: 2.2.3 Geen timing
moet zijn: 2.2.4 Onderbrekingen
=> fix: WCAG 2.2.4 change label in the WCAG sidebar

docs/community/events/design-systems-week-2023/1-programma.md, docs/community/events/design-systems-week-2023/2-tijdschema-per-dag.md, docs/community/events/design-systems-week-2023/english/1-program.md, docs/community/events/design-systems-week-2023/english/2-timetable.md, docs/community/events/design-systems-week-2024/english/index.md, docs/community/events/design-systems-week-2024/english/program.md, docs/community/events/design-systems-week-2024/english/timetable.md, docs/community/events/design-systems-week-2024/index.md, docs/community/events/design-systems-week-2024/programma.md, docs/community/events/design-systems-week-2024/tijdschema-per-dag.md, docs/community/events/design-systems-week/aanmelden-bedankt.mdx, docs/community/events/design-systems-week/aanmelden.mdx, docs/community/events/design-systems-week/sign-up-thanks.mdx, docs/community/events/design-systems-week/sign-up.mdx
https://codefornl.slack.com/archives/C02CWGL2M18/p1727418393325329
> Op de pagina's over de Design Systems Week staat niet overal vermeld om welk jaar het gaat. Na te hebben gezocht met een zoekmachine (duckduckgo) was ik vrolijk events van het tijdschema van 2023 in mijn agenda aan het zetten, omdat die pagina als eerste in de zoekresultaten stond.
> 
> Is het een idee om het jaartal in de h1 te zetten bij Programma en Tijdschema? Op de pagina [Programma](https://www.nldesignsystem.nl/events/design-systems-week-2024/programma) is de eerste heading op de pagina trouwens een h2.
=> docs: add year to design systems week pages

docs/community/events/design-open-hour/design-open-hour.mdx, docs/community/events/developer-open-hour/developer-open-hour.mdx, docs/community/events/heartbeat/heartbeat.mdx, src/css/custom.css
https://codefornl.slack.com/archives/C02CWGL2M18/p1727417749645349
> [@Yolijn](https://codefornl.slack.com/team/U01B7T1F24S)
ik stel voor dat we voor alle community events een "Link that looks like a button" gebruiken, een CTA link zeg maar. Het is echt te subtiel. Als ik iemand een linkje wil sturen om zich aan te melden, dan wil ik liefst een linkje sturen naar de pagina over de heartbeat, zodat ze nog even extra het gevoel krijgen "ja dat wil ik, tof!" in plaats van direct naar het formulier voor "geen ons je data!", dat is zo transactioneel :sweat_smile: Maar elke keer ben ik bang dat ze afhanken omdat ze het linkje niet vinden
=> feat: cta-links for events

docs/handboek/component-bijdragen/community-stappenplan.mdx
Clarify the steps to publish a new version of `@nl-design-system/component-progress` and update the dependency in the `documentatie` repository. 
Fix typo.
=> docs: improve manual publish steps for component-progress

.changeset/wcag-3.3.md, docs/richtlijnen/formulieren/multistep/2-location/_guideline.md, docs/richtlijnen/formulieren/placeholder/4-colour-contrast/_guideline.md, docs/richtlijnen/formulieren/questions/4-avoid-duplicate-work/_guideline.md, docs/wcag/3.3.06.mdx, docs/wcag/summaries/_3.3.6-summary.md
Voegt pagina "3.3.6 Foutpreventie (alle)" toe.
Gerelateerd issue https://github.com/nl-design-system/documentatie/issues/1304 en
https://github.com/nl-design-system/documentatie/issues/1286
Preview: https://documentatie-git-docs-wcag-336-summary-nl-design-system.vercel.app/wcag/3.3.6
Omdat de inhoud hetzelfde is als [WCAG Succescriterium 3.3.4 Foutpreventie (wettelijk, financieel, gegevens)](https://nldesignsystem.nl/wcag/3.3.4), alleen de toepassing anders, is voor de bronnen en het testen verwezen naar die pagina.
Deze pagina kan dus als compleet beschouwd worden.
=> docs: WCAG-pagina 3.3.6 Foutpreventie (alle)

.changeset/wcag-2.3.2-summary.md, docs/wcag/2.3.01.mdx, docs/wcag/2.3.02.mdx, docs/wcag/summaries/_2.3.1-summary.md, docs/wcag/summaries/_2.3.2-summary.md
Gerelateerd issue: #1304
Previews:
https://documentatie-git-docs-wcag-232-summary-nl-design-system.vercel.app/wcag/2.3.2
https://documentatie-git-docs-wcag-232-summary-nl-design-system.vercel.app/wcag/2.3.1
De tekst van 2.3.1 is iets uitgebeid om het verschil met 2.3.2 beter te beschrijven.
=> docs: WCAG 2.3.2 Drie flitsen summery en tekstaanpassing 2.3.1 Drie flitsen of beneden drempelwaarde

docs/richtlijnen/formulieren/error/3-clarity/README.mdx
De regel ‘keywords’ was weggevalen en daardoor werden de keywords aan de slug van de pagina /richtlijnen/formulieren/foutmeldingen/duidelijk toegevoegd.
=> fix: Fout in slug /richtlijnen/formulieren/foutmeldingen/duidelijk

.changeset/wcag-2.4.12-summary.md, docs/wcag/2.4.12.mdx, docs/wcag/summaries/_2.4.12-summary.md
Voegt pagina met samenvatting "2.4.12 Focus niet bedekt (uitgebreid)" toe.
Preview: https://documentatie-git-docs-wcag-2412-summary-nl-design-system.vercel.app/wcag/2.4.12
=> docs: WCAG 2.4.12 Focus niet bedekt (uitgebreid) - summary

.changeset/wcag-2.4.8-summary.md, docs/wcag/2.4.07.mdx, docs/wcag/2.4.08.mdx, docs/wcag/summaries/_2.4.8-summary.md
Voegt pagina met samenvatting "WCAG-pagina 2.4.8 Locatie" toe.
Preview: https://documentatie-git-docs-wcag-248-summary-nl-design-system.vercel.app/wcag/2.4.8
=> docs: WCAG 2.4.8 Locatie - summary

.changeset/wcag-3.1.3-summary.md, docs/wcag/3.1.03.mdx, docs/wcag/summaries/_3.1.3-summary.md
Voegt pagina met samenvatting "3.1.3 Ongebruikelijke woorden" toe.
Preview: https://documentatie-git-docs-wcag-313-summary-nl-design-system.vercel.app/wcag/3.1.3
=> docs: WCAG 3.1.3 Ongebruikelijke woorden - summary

docs/handboek/component-bijdragen/help-wanted-stappenplan.mdx
Links naar DSO leidde naar verouderde versie van hun Design System. Hierdoor linken we altijd naar de laatste versie. En zal men via de documentatie website naar de Storybook moeten navigeren.
=> fix: link naar dso bijgewerkt

.changeset/wcag-2.5.6-summary.md, docs/wcag/2.5.05.mdx, docs/wcag/2.5.06.mdx, docs/wcag/summaries/_2.5.6-summary.md
Voegt pagina met samenvatting "2.5.6 Input gelijktijdige invoermechanismen" toe.
Preview: https://documentatie-git-docs-wcag-256-summary-nl-design-system.vercel.app/wcag/2.5.6
=> docs: WCAG 2.5.6 Input gelijktijdige invoermechanismen - summary

docs/wcag/0-introduction.mdx
Gerelateerd: #1304.
Preview: https://documentatie-git-docs-wcag-update-intro-page-nl-design-system.vercel.app/wcag/
=> docs: WCAG intro-pagina: links naar complete lijst succescriteria

.github/dependabot.yml, package.json
Group all patch and minor version updates into one pull requests.
Dependabot pull requests are normally not merged because we use our own pnpm update-patch/minor/major scripts to create pull requests. Dependabot pull requests mainly serve as a reminder. This change should bring down the number of pull requests down significantly while still serving as a reminder.
For major version bumps Dependabot will still open individual pull requests.
Bump package.json#packageManager
=> chore: update dependabot.yml + package.json#packageManager

docs/community/events/design-systems-week-2024/english/program.mdx, docs/community/events/design-systems-week-2024/programma.mdx, docs/community/events/design-systems-week-2024/sessions.json, docs/community/events/design-systems-week-2024/tijdschema-per-dag.mdx, src/components/DSWSession.tsx, src/components/SessionTable.tsx
Op veler verzoek: tijden in het programma.
Nederlands:
Engels:
De linkjes worden automatisch verborgen wanneer later de video beschikbaar is.
=> feat: add link to iCal from DSW program pages

docs/community/events/design-systems-week-2024/programma.mdx, src/components/DSWSession.tsx
tolktekstlinks zijn anders per schrijftolk, dit voegt ze toe aan de sessies waarvan we de link to nu toe hebben, en plaatst ze in het programma. 
ik had niet heel veel inspiratie, zo ziet het eruit (met visuallyhidden nog de naam van de sessie voor linkuniekheid)
=> docs: add captionlinks

docs/community/events/community-bijeenkomst-2.mdx
Nu we het linkje steeds delen in de Teams chat tijdens de Design Systems week is het goed om de pagina wat meer context te geven als je er later op terecht komt.
Zowel Rian als Savi (van Frameless) merkten dit op.
=> docs: improve communitybijeenkomst with discription

docs/componenten/button/_wcag-1.1.1.md, docs/componenten/button/_wcag-1.4.11.md, docs/componenten/button/_wcag-1.4.12.md, docs/componenten/button/_wcag-1.4.3.md, docs/componenten/button/_wcag-1.4.4.md, docs/componenten/button/_wcag-1.4.5.md, docs/componenten/button/_wcag-2.4.13.md, docs/componenten/button/_wcag-2.4.6.md, docs/componenten/button/_wcag-2.4.7.md, docs/componenten/button/_wcag-2.5.3.md, docs/componenten/button/_wcag-2.5.5.md, docs/componenten/button/_wcag-3.2.4.md
Gerelateerd: https://github.com/nl-design-system/documentatie/issues/1375
Preview: https://documentatie-git-docs-linkfix-button-co-b33ac9-nl-design-system.vercel.app/button
Twee links klopten niet meer. Aantal links toevoegen nu Rian de stijlrichtlijnen opnieuw heeft ingedeeld.
=> docs: linkfixes button component pagina

docs/community/events/design-systems-week-2024/programma.mdx
- het ID van Thijs's sessie was die van Steve, waardoor de tijd verkeerd stond ([regel 259](https://github.com/nl-design-system/documentatie/pull/1537/files#diff-deaf921c09ac11ceae913f6eb719e2f2fddd3462a83274eb62230226c696451bL259))
- door Hui Jing's sessie klopte de volgorde (op naam) niet meer, dat dus ook aangepast
=> fix: fix uuid

docs/richtlijnen/_footer_info.md
Gebroken link : “Deel je mening op GitHub met je suggesties” verwijst naar een gesloten discussie en de tekst is krom.
Nieuwe tekst: Open een issue op GitHub en deel je mening.
=> fix: Gebroken link en kromme zin bij de Opmekingen-include van de richtlijnen.

.github/dependabot.yml, package.json, pnpm-lock.yaml
- update package.json#packageManager to include hash
- align @types/node with the node version in the repo and prevent Dependabot from updating @types/node to a new major version
=> chore: packagemanager

docs/community/events/design-systems-week-2024/english/index.mdx, docs/community/events/design-systems-week-2024/english/program.mdx, docs/community/events/design-systems-week-2024/english/timetable.mdx, docs/community/events/design-systems-week-2024/index.mdx, docs/community/events/design-systems-week-2024/programma.mdx, docs/community/events/design-systems-week-2024/sessions.json, docs/community/events/design-systems-week-2024/tijdschema-per-dag.mdx, src/components/DSWSession.tsx
Updates aan content:
- DSW 2024 tekst herschreven naar de verleden tijd
- call to actions aangepast naar dat je video's kunt kijken (in de toekomst evt nog uitbreiden met generieke DSW nieuwsbrief aanmelding oid)
- Robbert's sessienaam aangepast naar “Aan de slag met NL Design System”
- in Robberts omschrijving de `<Link>` aangepast naar `<a>` zodat de Prettier-Markdown-combo de link niet per ongeluk in een `<p>` wrapt
Updates aan data:
- heb videoId's in de `sessions.json` gezet
- Geri's UUID goed gezet (woops)
Updates aan componenten:
- datum + icallink weergeven bij sessie in `DSWSession` doen we nu alleen als die in de toekomst ligt 
- videoweergave bij een sessie werkt nu in `DSWSession` met videoId op het component zelf, of met videoId in de `sessions.json` (voor backwards compat …
=> Add Design Systems Week 2024 videos

src/pages/index.tsx
Bevat nu de tekst uit het logo en beschrijving van linkbestemming.
fixes #416
=> Update link text to be more explicit about destination

src/theme/Navbar/Layout/index.tsx, src/theme/Navbar/MobileSidebar/Layout/Layout.module.css, src/theme/Navbar/MobileSidebar/Layout/index.tsx, src/theme/Navbar/MobileSidebar/Toggle/index.tsx
Wat is anders: 
- mobile nav nu niet meer een `div` maar een `dialog`
- om mobile nav te openen gebruiken we nu `showModal()`, via `useEffect` hook om zeker te weten dat er altijd als er een `dialog` is er de juiste methodes aangeroepen worden
- we checken ook op `Escape`: sluiten krijg je gratis van de browser, maar we willen ook de `shown` state bijwerken zodat het bij volgende menu-button-klik ook weer werkt
Known issues: 
- Op pagina's met submenu's zoals Handboek zijn er nog steeds een paar onzichtbare tab stops, die zijn er ook live, dus geen regressie, en zitten in de mobile nav zelf; to be fixed in een andere PR
fixes #413
=> feat: use dialog element for mobile nav

src/css/custom.css
fixes #412 
extra's: vergroot ook de font-size van de keyboard short cut en de breedte van de modal.
=> fix: use 4.5:1 contrast for placeholder color and background

src/components/Guideline.tsx
Bij richtlijnen staat een svg'tje met een smiley bij 'Doen' of 'Niet doen'.
Deze PR voegt aan het `<svg>` element voor beide zowel `role="presentation"` als `aria-hidden="true"` toe, voor max browser support.
fixes #1723
=> Markeer icons bij richtlijn als decoratief

.changeset/ac-keybordtrap.md, docs/componenten/button/index.mdx, docs/componenten/link/index.mdx, docs/componenten/login-link/index.mdx
Rerelateerd issue: https://github.com/nl-design-system/documentatie/issues/1635
Previews
- [Button](https://documentatie-git-docs-components-adds-k-3bf871-nl-design-system.vercel.app/button)
- [Login Link](https://documentatie-git-docs-components-adds-k-3bf871-nl-design-system.vercel.app/login-link)
- [Link](https://documentatie-git-docs-components-adds-k-3bf871-nl-design-system.vercel.app/link)
=> docs: WCAG 2.1.2 Geen toetsenbordval toevoegen aan AC componenten Button, Link en Login Link

src/theme/Navbar/MobileSidebar/Layout/index.tsx
Als je de mobiele nav van een pagina met submenu opende, zag je alleen het submenu, maar kon je tabben door hoofdmenu + submenu. Dat is een 2.4.7 probleem. 
De bestaande code zorgde met CSS dat je hoofdmenu en submenu niet tegelijk zag. Met deze PR rendereren we überhaupt alleen hoofdnav of alleen subnav.
fixes #1728
=> Haal niet-zichtbare menu-items uit DOM en tabvolgorde

docs/componenten/ac/_wcag-1.4.11-code.md
Gerelateerd issue: #1738 
ZIn toegevoegd over uitzondering als lettertype of weergave anders is.
Preview: https://documentatie-git-docs-ac-component-code-e50e60-nl-design-system.vercel.app/code-block
=> docs: Acceptatiecriteria Code Block, aanscherpen WCAG 1.4.11

docs/componenten/ac/_ac_intro.md, docs/componenten/button/index.mdx, docs/componenten/code-block/index.mdx, docs/componenten/code/index.mdx, docs/componenten/color-sample/index.mdx, docs/componenten/data-badge/index.mdx, docs/componenten/heading/index.mdx, docs/componenten/link/index.mdx, docs/componenten/login-link/index.mdx, docs/componenten/mark/index.mdx, docs/componenten/number-badge/index.mdx, docs/componenten/paragraph/index.mdx, docs/componenten/skip-link/index.mdx, docs/richtlijnen/README.mdx, docs/richtlijnen/stijl/colour/3-purpose/_guideline.md, docs/richtlijnen/stijl/colour/4-dont-trust/_guideline.md, docs/richtlijnen/stijl/colour/5-perception/_guideline.md, docs/richtlijnen/stijl/colour/6-settings/_guideline.md, docs/richtlijnen/stijl/space/4-relations/_guideline.md, docs/richtlijnen/stijl/space/README.mdx
Duidelijk vermelden aan welke WCAG-succescriteria we willen voldoen, inclusief de AAA.
Gerelateerd:
- #1556
- #1742
=> Docs: Aangeven welke WCAG 2.2 AAA succescriteria we ook aanhouden

src/theme/SearchBar/index.tsx
Known issue: wanneer je 'm sluit met een klik buiten de is de `focus-visible` stijl niet zichtbaar, terwijl die wel gebruikt wordt als je met keyboard sluit. Geverifieerd dat de focus zich ook in dat geval wel netjes verplaatsten je vanuit de button naar vorige/volgende elementen kunt tabben.
=> Geef focus terug aan zoekknop na sluiten zoekmodal (fixes #1733)

docs/community/events/community-bijeenkomst-2.mdx, docs/community/events/design-open-dag.mdx, docs/community/events/design-open-hour/aanmelden.mdx, docs/community/events/design-systems-week-2023/1-programma.md, docs/community/events/design-systems-week-2023/english/1-program.md, docs/community/events/design-systems-week-2024/english/program.mdx, docs/community/events/design-systems-week-2024/programma.mdx, docs/community/events/design-systems-week/aanmelden.mdx, docs/community/events/design-systems-week/sign-up.mdx, docs/community/events/developer-open-hour/aanmelden.mdx, docs/community/events/estafettemodeldag.mdx, docs/community/events/heartbeat/aanmelden.mdx, docs/community/sluit-je-aan.mdx, docs/project/blijf-op-de-hoogte.mdx, src/components/DSWSession.tsx, src/components/NewsletterSignUp.tsx
Default imports appear to cause various issues, depending on the mdx processor
=> refactor: avoid default imports in MDX

src/pages/contrast/index.tsx
Op basis van feedback van Joost van der Steen en Johan Huijkman.
https://documentatie-git-docs-contrast-nl-design-system.vercel.app/contrast/
- Je ziet het gelijk in actie
- Voorbeelden van welke CSS-waarden okay zijn
- Geen code als formulierveldlabels
=> docs: add color contrast clarification

docs/componenten/heading/index.mdx, docs/componenten/link/index.mdx, docs/componenten/mark/index.mdx, docs/componenten/skip-link/index.mdx
Adds anatomy + aliases for heading, link, mark and skip link.
Not for number badge ([not public yet](https://github.com/nl-design-system/candidate/blob/main/packages/docs/number-badge-docs/package.json#L23), [PR pending](https://github.com/nl-design-system/candidate/pull/343)), paragraph (paths are not consistent with the others, see [same PR](https://github.com/nl-design-system/candidate/pull/343)) or heading 1 t/m 6 (we haven't added their anatomy, aliases yet; added in [PR 344](https://github.com/nl-design-system/candidate/pull/344)).
=> Add anatomy + aliases for Heading, Link, Mark and Skip Link

src/components/ComponentAnatomy.tsx, svgr.config.js
Ik had de hoop bijna opgegeven, na svgr config te proberen te zetten via Docusaurus settings en plugins, tot @matijs op het idee kwam dat svgr de settings uit een los settinggbestandje misschien wel gewoon oppikt. En dat doet ie. Zo hoeven we niet meer de extra role toe te voegen.
=> Zorg dat img role op svgs gezet door svgr

.changeset/ac-word-break.md, docs/componenten/ac/_wcag-1.4.12.md, docs/componenten/ac/_wcag-1.4.4.md, docs/wcag/summaries/_1.4.10-summary.md, docs/wcag/summaries/_1.4.12-summary.md, docs/wcag/summaries/_1.4.4-summary.md
Voor WCAG-SC [1.4.4 Herschalen van tekst](https://nldesignsystem.nl/wcag/1.4.4/), [1.4.10 Reflow](https://nldesignsystem.nl/wcag/1.4.10/) en [1.4.12 Tekstafstand](https://nldesignsystem.nl/wcag/1.4.12) moet het mogelijk zijn om lange woorden af te breken en te laten doorlopen op de volgende regel. Dit om een horizontale scrollbar te voorkomen.
Voorgestelde tekst:
Definieer in de CSS een wijze om lange woorden af te breken en te laten doorlopen op de volgende regel. Zodat er geen horizontale scrollbar ontstaat of tekst onleesbaar wordt.
Toevoegen bij de acceptatiecriteria van de componenten:
componenten/ac/_wcag-1.4.4.md
componenten/ac/_wcag-1.4.12.md
Toevoegen bij de summaries van de WCAG-pagina's:
wcag/summaries/_1.4.4-summary.md
wcag/summaries/_1.4.10-summary.md …
=> docs: Bij acceptatiecriteria componenten word-break mogelijkheid vermelden bij reflow en herschalen

src/components/ComponentOverview.tsx
(turns out… losing focus is default behavour of history.push() in React Router, but not of history.replace(); this seems coincidental, this change also means that there is no history kept of the different filter settings, I think that's ok)
--- 
Dit fixt twee dingen: 
- focus werd bij veranderen filter terugverplaatst naar body, dat gebeurt nu niet meer
- filters gaan nu automatisch open als je in de URL filters had staan (bv als iemand het met je deelde)
=> Fix focus issue in component filter

src/css/custom.css
(fixes https://github.com/nl-design-system/documentatie/issues/1729)
Door een te breed gescopete CSS-regel plakten `p`'s vast aan de `ul`'s erboven, zoals hier:
Dit PR maakt een einde aan deze praktijk: 
de `margin: 0 auto` was specifiek om in de search modal de juiste uitlijning te bewerkstelligen, maar gescoped op alle ul's in docpagina's.
=> Fix ruimte onder ul's 

docs/componenten/link/index.mdx
We gaan in 2025 Q1 de consistente focus-indicator code aanpakken wanneer we voldoende focusable componenten hebben
=> docs: suspend Level AAA focus-indicator requirement until 2025Q1

.changeset/remove-wcag-2.4.13-for-now.md, docs/componenten/ac/_ac_intro.md, docs/componenten/ac/_wcag-2.4.7.md, docs/componenten/button/index.mdx, docs/componenten/login-link/index.mdx, docs/componenten/skip-link/index.mdx, docs/wcag/2.4.07.mdx
Deze PR verwijderd (naast Link) ook het acceptatiecriterium 2..3.13 voor de componenten 
- Button
- Link
- Skip Link
- Login Link
en verwijzingen in de documentatie.readme
Gerelateerd
Issue: https://github.com/nl-design-system/documentatie/issues/1836
PR van 19 december '24 https://github.com/nl-design-system/documentatie/pull/1835
=> docs: Verwijder tijdelijk de 2.4.13 focus indicator uit de acceptatiecriteria voor de Camdidate componenten

docs/componenten/color-sample/index.mdx
Voegt WCAG-succescriterium 1.4.1 Gebruik van kleur toe aan acceptatiecrieria van Color Sample. Deze ontbrak nog.
=> docs: Voegt WCAG-succescriterium 1.4.1 Gebruik van kleur toe aan acceptatiecrieria van Color Sample

docs/community/events/design-open-dag.mdx
Deze PR haalt de data uit 2024 weg en toont enkel nog de aanstaande data voor de komende 5 maanden in 2025.
=> docs: update planning design open dag

.changeset/wcag-1.4.1-full-page.md, docs/richtlijnen/formulieren/visual-design/6-use-of-color/_guideline.md, docs/wcag/1.4.01.mdx
Volledige pagina voor WCAG-succescriterium 1.4.1 Gebruik van kleur.
Issue: https://github.com/nl-design-system/documentatie/issues/640
Tracking issue: https://github.com/nl-design-system/documentatie/issues/1408
Preview: https://documentatie-git-docs-wcag-141-full-nl-design-system.vercel.app/wcag/1.4.1
=> docs: WCAG 1.4.1 full page

static/heartbeat/heartbeat.ics
de oude heartbeat url werkt nog wel, maar is gekoppeld aan het account van Hidde waar we niet meer bij kunnen. Als we de video's weer willen kunnen uploaden dan is het handiger om deze nieuwe url te gebruiken.
We hebben getest dat:
1. de video in deze nieuwe url opgenomen kan worden door andere kernteam leden
2. deze opname door hen te downloaden is en op youtube gezet kan worden
3. de url toegevoegd kan worden aan het bestaande ics bestand om automatische updates voor mensen met een koppeling mogelijk te maken.
4. de nieuwe url werkt in het .isc bestand
De url gaat soms naar de chat waar je nog op 'join' moet drukken en soms naar de meeting zelf. Gekke is dat het om dezelfde url gaat, dus heb het voor nu even gelaten.
Voor 21 jan: verstuur een mail naar de heartbeat mailinglist in …
=> fix: heartbeat url

.changeset/docs-button-text.md, docs/richtlijnen/formulieren/button/4-text/_guideline.md
Aanpassen advies button tekst naar aanleiding van discussie #1894
Het advies voor de buttotekst is nu gelijk aan wat we gaan gebruiken in het template voor meerstappenformulieren.
Besloten door @jeffreylauwers en @rianrietveld 
Preview: https://documentatie-git-docs-button-text-nl-design-system.vercel.app/richtlijnen/formulieren/buttons/duidelijk-buttontekst
=> docs: richtlijnen: aanpassing richtlijn buttontekst van formulieren

.changeset/docs-tekst-verplicht-veld.md, blog/2024/20240624-toegankelijke-foutmeldingen.md, docs/richtlijnen/formulieren/help/1-show-required/_mark-optional-fields-code.mdx, docs/richtlijnen/formulieren/help/1-show-required/_mark-required-fields-code.mdx
Naar aanleiding van discussie https://github.com/nl-design-system/documentatie/issues/1896
Tekst aangeven verplichte velden vereenvoudigd.
Besloten door @jeffreylauwers en @rianrietveld
Preview:
https://documentatie-git-docs-tekst-verplichte-velden-nl-design-system.vercel.app/richtlijnen/formulieren/voorkom-fouten/verplichte-velden/
Ook de tekst van de blogpost Toegankelijke foutmeldingen in formulieren is aangepast.
Preview:
https://documentatie-git-docs-tekst-verplichte-velden-nl-design-system.vercel.app/blog/toegankelijke-foutmeldingen-formulieren
=> docs: richtlijnen: tekst foutmeldingen eenvoudiger

.changeset/richtlijnen-voortgang.md, docs/richtlijnen/formulieren/multistep/1-step-count/_code.mdx, docs/richtlijnen/formulieren/multistep/1-step-count/_guideline.md, docs/richtlijnen/formulieren/multistep/2-location/_code.mdx, src/components/Guideline.css
Naar aanleiding van discussie https://github.com/nl-design-system/documentatie/issues/1895
Optie toevoegen op de stappenvoortgang op te nemen in het kopje en visueel via CSS op een andere regel te plaatsen.
Besloten door @jeffreylauwers en @rianrietveld
Twee voorbeelden toegevoegd, preview:
- https://documentatie-git-docs-voortgang-nl-design-system.vercel.app/richtlijnen/formulieren/meerdere-stappen/voortgang-tonen
- https://documentatie-git-docs-voortgang-nl-design-system.vercel.app/richtlijnen/formulieren/meerdere-stappen/plaatsing-voortgang
Keuze vastgelegd in GitHub Discussion voor een Meerstappenformulier:
https://github.com/orgs/nl-design-system/discussions/364#discussioncomment-11840898
=> docs: Richtlijnen: Voorbeeld toevoegen voortgang meerstappenformulier opnemen in het kopje en visueel scheiden via CSS

blog/2025/20250125-stappen-a-status-website.md
Preview: https://documentatie-git-fix-typos-in-blogpost-a6dee2-nl-design-system.vercel.app/blog/tips-9-stappen-A-status-website
=> fix: typos en urls blogpost 9 stappen de a-status

docs/community/events/heartbeat/heartbeat.mdx
Based on this year:
- second session in january skipped
Based on overlapping summer holiday from https://www.rijksoverheid.nl/onderwerpen/schoolvakanties/zomervakantie/zomervakantie-2025 which is 19 juli to 17 august.
Based on last year: only one in december
=> docs: update heartbeat planning for 2025

docs/handboek/component-bijdragen/help-wanted-stappenplan.mdx
- Checkpoint 'nldesignsystem' opgesplitst en uitgebreid.
- Checkpoints 'nldesignsystem' en 'status' omgewisseld.
- GitHub overal gelijk geschreven.
- Opzet van schrijfwijze gelijk getrokken voor invullen van branch namen, commit messages, discussions en backlog issues gelijk getrokken.
- Hier en daar kleine tweaks die mooi meegenomen waren.
=> docs: update help wanted stappenplan

docs/handboek/component-bijdragen/community-stappenplan/voor-kernteam.mdx, docs/handboek/component-bijdragen/community-stappenplan/voor-organisaties.mdx, docs/handboek/component-bijdragen/definition-of-done.mdx
**Community Stappenplan voor kernteam**
- Opzet van schrijfwijze gelijk getrokken omdat dit het Community stappenplan voor het kernteam zelf betreft.
- Checkpoint 'nldesignsystem' gelijk getrokken met Help Wanted stappenplan.
- Checkpoint 'promotie' opgesplitst in verband met component progress.
- Fout in 'Status bijwerken' eruit.
- Dubbeling van component progress er uit.
- Tip over minimale tokens toegevoegd.
- Hier en daar kleine tweaks die mooi meegenomen waren.
**Definition of done**
- Heading uit Stappenplan gelijk getrokken met item in opsomming.
- Positie aangepast.
**Community Stappenplan voor community**
- Opzet van schrijfwijze gelijk getrokken omdat dit het Community stappenplan voor de community zelf betreft.
- Tip over minimale tokens toegevoegd.
- Hier en daar kleine tweaks …
=> docs: update community stappenplan

.github/CODEOWNERS
By popular demand: trigger code reviews in certain documents
=> chore: trigger a11y-reviews via CODEOWNERS

docs/footer/colofon.mdx
Ben contacted us that the icon license has changed to CC0, which means no mention of OpenGemeenten is required anymore 🥳
=> chore: remove open gemeenten from colofon.

docs/handboek/component-bijdragen/community-stappenplan/voor-organisaties.mdx
=> docs: Feedback op stap "Voeg de component toe aan een config" in het NLDS Community Stappenplan (#2021)

blog/2025/20250211-a11y-name-link-logo-header.md
Add front matter image to blog post so LinkedIn, etc show thumbnail when the blog post is linked. Image is already pushed to the assets branch and live.
=> feat: add front matter image to blogpost

docs/componenten/ac/_wcag-2.5.2-accordion.md, docs/componenten/ac/_wcag-4.1.2-accordion.md
- Dubbeling in tekst
- Opsomming zonder witregel.
- 'gebruikersinterface' in plaats van 'userinterface'.
- Extra spatie na `click` en voor event.
=> Update acceptatiecriteria accordion

docs/componenten/ac/_wcag-2.4.6-button.md
Op pagina https://nldesignsystem.nl/button stond onder Toegankelijkheid algemeen, 2.4.6 een link naar: https://nldesignsystem.nl/formulieren/meerdere-stappen/consistente-benaming/
Dit werkt niet, het moet zijn: 
https://nldesignsystem.nl/richtlijnen/formulieren/meerdere-stappen/consistente-benaming/
=> Fix 404 op foutieve link in button acceptatiecriteria

docs/handboek/component-bijdragen/help-wanted-stappenplan.mdx
- Fixed the mismatch between Figma en Stappenplan of naming the Schematische afbeelding.
- Changed hex values of svg adjustment (because the colors were changed in Figma).
- Added a tip to set all checkpoints on 'green' before kicking off the component progress.
=> Fix: update help wanted stappenplan

blog/2024/20240305-meerdere-manieren-contact.md, blog/2024/20240311-gebruikerstest-ondernemers.md, blog/2024/20240322-design-open-dag.md, blog/2024/20240522-community-blocks.md, blog/2025/20250125-stappen-a-status-website.md
Update all front matter images (page thumbnails) for blogposts to use raw.githubusercontent.com
=> fix: update github image links to raw.githubusercontent.com

docs/handboek/estafettemodel.mdx, src/components/ComponentOverview.tsx
- Add links for each component status from Estafettemodel page to component overview page
- Add "Toon alle componenten" button to component overview page when no component matches the filter
=> feat: add component overview links to estafettemodel

docs/handboek/organisatie/meedoen.md
Het is niet makkelijk uit te leggen wat niveau 7 precies betekend. Daarom is besloten deze te verwijderen.
=> docs: remove niveau van meedoen 7

.changeset/README.md, .changeset/ac-accordion.md, .changeset/ac-code-block.md, .changeset/ac-code.md, .changeset/ac-color-sample.md, .changeset/ac-keybordtrap.md, .changeset/ac-login-link.md, .changeset/ac-mark.md, .changeset/ac-word-break.md, .changeset/baseline.md, .changeset/docs-button-text.md, .changeset/docs-tekst-verplicht-veld.md, .changeset/remove-wcag-2.4.13-for-now.md, .changeset/richtlijnen-rich-text-kopjes.md, .changeset/richtlijnen-voortgang.md, .changeset/scheidingsteken.md, .changeset/wcag-1.3.3-full-page.md, .changeset/wcag-1.4.1-full-page.md
All these changes are for documentation repo, not nlds-design-tokens. The default is also documentation repo, which is why we updated the README.md in the .changeset folder.
Found when reviewing a PR with Renate.
Next step is to merge the publication PR, which was created in oct 2024: https://github.com/nl-design-system/documentatie/pull/1540.
=> chore: reference correct package in changesets

docs/handboek/designer/breaking-changes.md
[Handboek ➝ Voor designers ➝ Breaking Changes](https://documentatie-git-docs-designer-breaking-e75307-nl-design-system.vercel.app/handboek/designer/breaking-changes)
=> docs: add designer handboek "breaking changes"

.changeset/wcag-1.4.11-full-page.md, docs/wcag/1.4.03.mdx, docs/wcag/1.4.11.mdx, docs/wcag/summaries/_1.4.11-summary.md
Preview: [WCAG-succescriterium 1.4.11 Contrast van niet-tekstuele content](https://documentatie-git-docs-wcag-1411-full-nl-design-system.vercel.app/wcag/1.4.11)
=> Docs/wcag 1.4.11 full

docs/richtlijnen/stijl/space/2-boxing-model/README.mdx
De description van Box Model had dezelfde tekst als Spacing Scale. Aangepast zodat het bij de inhoud klopt.
=> Description Box Model correct aangepast

docs/community/events/design-open-hour/design-open-hour.mdx
Clarified that there is no fixed agenda and added a clearer explanation of how participants can view or add topics to the Slack agenda. Improves transparency and helps participants prepare.
=> docs: improve description of agenda process for design open hour

docs/community/events/design-open-dag.mdx
Added a paragraph explaining the use of the Slack agenda for the Design Open Dag. Encourages participation and better preparation by making the agenda accessible beforehand.
=> docs: add slack agenda link to design open dag

docs/handboek/designer/nieuwe-versie-publiceren/README.md, docs/handboek/designer/nieuwe-versie-publiceren/index.md, docs/handboek/designer/nieuwe-versie-publiceren/versiebeheer-voor-design-tokens.md, static/.htaccess
This commit adds a new overview page under the documentation section, explaining how version updates are handled for design tokens and Figma libraries. The page links to subpages about semantic versioning, working with the Figma changelog, and the changelog overview itself.
The goal is to help designers understand how to track changes, what kind of updates to expect, and how those are communicated.
=> feat: add overview page for publishing new versions

docs/handboek/designer/nieuwe-versie-publiceren/werken-met-changelog-voor-figma.md
Add 'Werken met changelog voor Figma' page.
The changelog link has been commented out temporarily. I’ll update it with the correct URL once the changelog page has been created.
=> feat: add werken met changelog voor figma page

docs/handboek/designer/nieuwe-versie-publiceren/_changelog-figma.md
Add 'Changelog Figma' page. 
This page is currently hidden, as we don’t have a changelog available yet. Once the first version of the changelog is ready, we’ll make this page visible on the website.
=> feat: add figma changelog page

docs/handboek/designer/nieuwe-versie-publiceren/_templates-changelog-figma-bibliotheken.md
Add 'Templates changelog Figma bibliotheken' markdown.
It is intended for internal use only and will remain hidden from the public website at all times.
=> feat: add templates for figma changelog

docs/project/global-design-system.mdx, docs/project/links.mdx, sidebarConfig.ts
> BTW could we have a list of our Design Systems somewhere here? (or more than just ours). Maybe pinned or in channel description or somewhere? Ours is Helsinki Design System (HDS) at hds.hel.fi
Naar aanleiding van [de vraag in Slack](https://codefornl.slack.com/archives/C08N9AJFAG0/p1745482148614329), heb ik de pagina in het Engels beschikbaar gemaakt: [Global design systems for governments](https://documentatie-git-docs-international-nl-design-system.vercel.app/project/global-design-system)
=> docs: global design system links

.changeset/wcag-1.4.10-full-page.md, docs/wcag/1.4.10.mdx, docs/wcag/summaries/_1.4.10-summary.md
2 punten van twijfel:
- Moet ik termen verder uitleggen of duiden? Sommige termen zijn vooral in het Engels goed vindbaar (zoals viewport) en dan is het gebruik van het Nederlandse "schermbreedte" misschien een drempel om meer informatie te vinden.
- Moet ik verder uitleggen hoe je iets in een browser moet doen? Het voelt nu wel vrij minimaal, maar het lijkt me ook niet de bedoeling om browser-documentatie te schrijven.
=> docs: wcag 1.4.10 full page

.changeset/cold-cycles-smell.md, docs/community/community-sprints/rijkshuisstijl-community.mdx, docs/community/events/rijkshuisstijl-community-open-hour/rijkshuisstijl-community-open-hour.mdx, sidebarConfig.ts
Met commented code waar we refereren naar de aanmeld pagina, welke in een latere iteratie word toegevoegd.
[RHC Open Hour preview.
](https://documentatie-git-feat-toevoegen-rijkshu-6ffbdf-nl-design-system.vercel.app/events/rijkshuisstijl-community-open-hour)
[RHC Community Sprint preview.](https://documentatie-git-feat-toevoegen-rijkshu-6ffbdf-nl-design-system.vercel.app/community/community-sprints/rijkshuisstijl-community)
=> feat: toevoegen rijkshuisstijl community open hour pagina

.changeset/audiodescription-headingache.md, docs/richtlijnen/content/video/audiodescriptie.md
In richtlijnen Audiodescriptie de eerste kop aangepast van h2 naar h1
=> Fix: kop van h2 naar h1

docs/handboek/designer/figma-structuur.mdx, docs/handboek/designer/stappenplan.mdx
Om bezoekers van nldesignsystem.nl te attenderen dat er werkzaamheden plaatsvinden rondom de Figma bibliotheken en documentatie plaatsen we een melding.
=> docs: spotlight voor melding werkzaamheden

.changeset/pixels-are-rem.md, docs/richtlijnen/stijl/typography/1-fontsize/_guideline.md
Doordat we via Tokens Studio rem kunnen gebruiken haal ik deze tekst liever weg om verwarring te voorkomen.
=> docs: pixel tekst verwijderd

docs/handboek/huisstijl-vastleggen/design-tokens.mdx
Positie van de Design token documentatie aangepast waardoor deze pagina qua volgorde boven de Thema documentatie te staat.
=> docs: sidebar positie van design tokens documentatie

.changeset/checklist-headings-text-change.md, docs/richtlijnen/content/README.mdx
De twee items leken qua tekst teveel op elkaar. Tekst aangepast zodat het duidelijkers is wat het onderscheid is en wat er moet gebeuren.
=> Tekst over koppen in content-checklist aangepast

static/.htaccess
No changeset needed, belongs with https://github.com/nl-design-system/documentatie/pull/2563
=> fix: add redirect for old reference to handboek design tokens

docs/community/community-sprints/rijkshuisstijl-community/rijkshuisstijl-community.mdx, docs/community/events/design-open-hour/design-open-hour.mdx, docs/community/events/design-systems-week-2024/programma.mdx, docs/community/events/developer-open-hour/developer-open-hour.mdx, docs/community/events/heartbeat/videos.mdx, docs/community/events/rijkshuisstijl-community-open-hour.mdx, docs/handboek/designer/introductie.mdx, docs/handboek/designer/werken-met-nl-design-system/_figma-changelog-templates.mdx, docs/handboek/designer/werken-met-nl-design-system/design-tokens-versiebeheer.mdx, docs/handboek/designer/werken-met-nl-design-system/figma-changelog.mdx, docs/handboek/designer/werken-met-nl-design-system/figma-migratie-stappenplan.mdx, docs/handboek/designer/werken-met-nl-design-system/figma-stappenplan.mdx, docs/handboek/designer/werken-met-nl-design-system/figma-structuur.mdx, docs/handboek/designer/zelf-componenten-maken.mdx, docs/handboek/huisstijl-vastleggen/design-tokens.mdx, docs/handboek/huisstijl-vastleggen/themas/start-thema.mdx
- Gebroken linkjes hersteld.
- Tijdelijke Spotlight sectie boven het Figma Stappenplan verwijderd.
=> docs: linkjes bijgewerkt

docs/community/events/heartbeat/videos.mdx, docs/handboek/component-bijdragen/community-stappenplan/voor-kernteam.mdx, docs/handboek/designer/introductie.mdx, docs/handboek/designer/werken-met-nl-design-system/figma-hygiene.mdx, docs/handboek/designer/zelf-thema-maken.mdx, docs/handboek/huisstijl-vastleggen/themas/voorbeeld-thema.mdx, docs/richtlijnen/formulieren/description/6-target-size/_guideline.md, docs/richtlijnen/stijl/icons/1-functional/_guideline.md, docs/richtlijnen/stijl/icons/2-toptasks/_guideline.md, docs/richtlijnen/stijl/icons/README.mdx, docs/richtlijnen/stijl/space/1-spacing-scale/_guideline.md, docs/richtlijnen/stijl/typography/4-font/_guideline.md
Met deze PR wordt er in de documentatie nu eerst naar het Start-thema verwezen. Daarnaast wordt de schrijfwijze gelijk getrokken met een streepje.
=> docs: verwijzen naar Start-thema en schrijfwijze met streepje

docs/handboek/huisstijl-vastleggen/themas/themas.mdx
Op de pagina Thema's staat nu nog 'Deze documentatie is nog in ontwikkeling.'. De content van '[Zelf een thema maken](https://www.nldesignsystem.nl/handboek/designer/zelf-thema-maken)' leent zich prima al opvulling. Onderaan wordt dan verwezen naar de specifieke documentatie voor developers en designers.
=> docs: documentatie voor Thema's

docs/componenten/code-block/index.mdx, docs/componenten/code/index.mdx, docs/componenten/color-sample/index.mdx, docs/componenten/data-badge/index.mdx, docs/componenten/heading/index.mdx, docs/componenten/link/index.mdx, docs/componenten/mark/index.mdx, docs/componenten/number-badge/index.mdx, docs/componenten/paragraph/index.mdx
De pagina's hadden nu niet allemaal dezelfde opbouw. Dat is niet voorspelbaar of handig. Op de https://nldesignsystem.nl/skip-link pagina stond hij nu goed, dus met deze PR is dat ook doorgevoerd voor de andere 9 Candidate componenten
De structuur in de sidebar is
1. Anatomie
2. Candidate component gebruiken
3. Acceptatiecriteria / Checklist voor toegankelijkheid
4. Community implementaties
5. Definition of Done
6. Help component verbeteren
=> chore: align page structure for candidate components

docs/componenten/table/index.mdx
Op de table pagina werd geen informatie uit Component Progress getoond én stond nog een gekke titel onderaan.
=> docs: fix table documentation

package.json, pnpm-lock.yaml
This PR will update the component progress to version 1.0.1-alpha.127.
Adds to https://github.com/nl-design-system/kernteam/issues/1367 and https://github.com/nl-design-system/kernteam/issues/1368.
Preview: [Page Footer](https://documentatie-git-build-update-component-e7ba3d-nl-design-system.vercel.app/page-footer/), [Page Header](https://documentatie-git-build-update-component-e7ba3d-nl-design-system.vercel.app/page-header/).
=> build: update component progress 1.0.1-alpha.127

docs/project/README.mdx, docs/project/_category_.json, navConfig.ts, sidebarConfig.ts
Fix voor ontbrekende taalcode in link (en begeleidende tekst) naar de global design systems-pagina.  
Gerelateerd issue: #2580  
- Taalcode toegevoegd aan de link  
- Begeleidende tekst aangepast
=> fix: ontbrekende taalcode toevoegen aan global design systems-link (#2580)

docs/project/slack.mdx, footerConfig.ts, sidebarConfig.ts
- nieuwe pagina met informatie over Slack, even 30 minuutjes lopen typen
- "Storybook" link in de Page Footer vervangen door "Slack"
- Storybook is niet erg representatief, dus goed dat die link weg is zonder context
- Slack is nu vindbaar in de homepage
- URL is nldesignsystem.nl/slack, zodat we die makkelijk kunnen aankondigen en ondertitelen in meetings
- tekst kan vast nog beter, maar dat kunnen we inplannen in een sprint
Branch deployment: [/slack/](https://documentatie-git-docs-slack-nl-design-system.vercel.app/slack/)
=> feat: add nldesignsystem.nl/slack for convenience
