nl-design-system/documentatie

patronen/formulieren-formulier-voorbereiden.md

Co-authored-by: HackMD <no-reply@hackmd.io>

docs:forms add hackmd badge (#6)

---

patronen/formulieren-formulier-voorbereiden.md
patronen/formulieren.md

Removed checkboxes from checklist as it is a redundant non-working feature.

Removed checkboxes from checklist

---

patronen/formulieren-afhandeling.md
patronen/formulieren-formulier-voorbereiden.md
patronen/formulieren-help.md
patronen/formulieren-overzicht.md
patronen/formulieren-questions-answers.md
patronen/formulieren-toegankelijkheid.md
patronen/formulieren-validation.md
patronen/formulieren-vormgeving.md
patronen/formulieren.md

* docs: forms - added correct menu item
* docs: forms - added correct menu item
* docs: forms - added document name
* docs: forms - added document name
* docs: forms - added document name
* docs: forms - added document name
* docs: forms - added document name
* docs: forms - added document name
* docs: forms - added document name
* docs: forms - added document name
* docs: forms - added document name
* docs: forms - put leading number in front of name to force menu sequence
* docs: forms - put leading number in front of name to force menu sequence
* docs: forms - put leading number in front of name to force menu sequence
* docs: forms - put leading number in front of name to force menu sequence
* docs: forms - put leading number in front of name to force menu sequence
* docs: forms - put …

Added document names and numbers so items appear in correct order (#11)

---

digid/digid-richtlijnen-afnemers.md

Added textcopy for DigiD guidelines

docs: digid guidelines

---

docs/patronen/04-iconografie/05-opengemeenten-iconen.md

Updated OpenGemeenten iconography documentation:
- Added link to Creative Commons licence for Illustrator icongrid file
- Updated iconset and design spec images

Iconography updates

---

docs/meedoen/03-als-designer/05-figma/12-figma-resources.md

Fix for Figma resources, closes #67

---

docs/richtlijnen/03-kleuren.md

Kleuren update

---

docs/richtlijnen/stijl/typografie.md

'Sidebar position' toegevoegd en bold teksten ingewisseld voor headings.

Position and headings

---

docs/richtlijnen/stijl/ruimte.md

'Sidebar position' toegevoegd en bold teksten ingewisseld voor headings.

Position en Headings

---

docs/meedoen/design-tokens/README.mdx

Origineel laten staan. Te vinden direct na '--- Tot hier ---'.

Aanvulling vanuit design perspectief

---

docs/meedoen/design-tokens/README.mdx

Ik ben er vanmorgen toch nog even met een frisse blik doorheen gegaan 😇.
**Wat heb ik waarom aangepast?**
- (enzovoorts) naar 'et cetera' --> Kwam dit woord letterlijk tegen in https://www.nldesignsystem.nl/richtlijnen/tekst-en-taalgebruik#algemene-afkortingen
- "thema" --> Met enkele aanhalingstekens. https://www.nldesignsystem.nl/richtlijnen/tekst-en-taalgebruik#aanhalingstekens
- een zin met '..., waarin...' --> Opgeknipt naar 2 zinnen.
- 'Elke organisatie maakt een eigen bestand met een "thema"...' --> Heb ik onder gebracht bij het hoofdstuk 'Thema' (incl de afbeelding)
- 'Iedere organisatie heeft zijn eigen huisstijl. Die huisstijl leg je vast in je eigen JSON file. Zo creëer je een eigen thema.' --> Werd daarom overbodig.
- 'Dat kan een breed scala aan ...' --> Die zin heb ik nooit …

Frisse blik

---

docs/richtlijnen/stijl/iconen.md
docs/richtlijnen/stijl/kleuren.md
docs/richtlijnen/stijl/ruimte.md
docs/richtlijnen/stijl/typografie.md

Contact link onderaan de pagina voorzien van een file path link

File path links

---

docs/componenten/_component-naamgeving.md

Placeholder voor component naamgeving. Nu vooral voor [Component] as [Button/Link] documentatie.

Component naamgeving

---

docs/meedoen/design-tokens/_design-tokens-volgorde.md

Placeholder voor de design token volgorde documentatie

Design token volgorde

---

docs/meedoen/als-designer/figma-structuur.mdx

'hebben' toegevoegd dankzij feedback Nico

Schrijffoutje

---

docs/richtlijnen/stijl/typografie.md

Kleine tekstwijziging

---

docs/meedoen/als-designer/voorbeeld-thema.md

Function naar Toptask

---

docs/componenten/README.mdx
src/components/CardGroup.module.css
src/components/ComponentCard.module.css
src/components/HomepageFooter.module.css
src/css/custom.css
src/pages/index.tsx
src/theme/DocBreadcrumbs/styles.module.css
src/theme/DocSidebar/Desktop/Content/styles.module.css
src/theme/DocSidebar/Desktop/styles.module.css
src/theme/DocSidebarItem/Category/index.tsx
src/theme/DocSidebarItems/index.tsx
src/theme/Navbar/Logo/Logo.module.css
src/theme/Navbar/MobileSidebar/Header/Header.module.css

fix: ux on mobile

---

docs/meedoen/als-designer/README.md
docs/meedoen/als-designer/community.md
docs/meedoen/als-designer/figma-structuur.mdx
docs/meedoen/als-designer/stappenplan.mdx
docs/meedoen/als-designer/voorbeeld-thema.md

Description teksten bijgewerkt voor 'Meedoen als designer' pagina's

Description teksten

---

docs/project/blijf-op-de-hoogte.mdx

We hadden op de pagina nog staan dat hij aangekondigd zou worden, dus nu met een snippet van de aankondiging en wat linkjes
https://nldesignsystem.nl/project/blijf-op-de-hoogte#nl-design-system-week
https://documentatie-git-docs-update-op-de-hoog-0055a0-nl-design-system.vercel.app/project/blijf-op-de-hoogte#nl-design-system-week

docs: add design system week

---

docs/project/events/design-systems-week-2023/1-programma.md
docs/project/events/design-systems-week-2023/english/1-program.md

Descriptions were still missin, this PR adds them.

Add Mu-Ans descriptions

---

docs/meedoen/als-designer/README.md
docs/meedoen/als-designer/figma-structuur.mdx
docs/meedoen/als-designer/stappenplan.mdx

Tekst, video's en afbeeldingen bijgewerkt vanwege nieuwe indeling token sets

docs: update Figma stappenplan

---

docs/project/events/design-systems-week-2023/1-programma.md
docs/project/events/design-systems-week-2023/2-tijdschema-per-dag.md
docs/project/events/design-systems-week-2023/english/1-program.md
docs/project/events/design-systems-week-2023/english/2-timetable.md
docs/project/events/design-systems-week-2023/speakers.json
src/components/DSWSession.module.css
src/components/DSWSession.tsx
src/components/SessionTable.module.css
src/components/SessionTable.tsx
src/css/custom.css

- Add last two talks
- Restyle table to have a nicer layout for name + organisation especially for multiple speakers
- add speaker images for management panel based on linkedIn and Slack
- add localisation to session time for international pages

Add sessions

---

docs/meedoen/design-tokens/README.mdx

Ik heb getracht de huidige documentatie samen te voegen met de documentatie die Robbert en ik eerder schreven maar die enkel nog als md bestand beschikbaar was.
https://github.com/nl-design-system/documentatie/blob/main/docs/meedoen/design-tokens/_design-tokens-volgorde.md

Design tokens naamgeving en volgorde update

---

static/.htaccess

chore: fix directory index

---

docs/richtlijnen/formulieren/5-maak-het-makkelijk.mdx

voegt “Maak het makkelijk” toe en die bevat [formulierfouten 7, 12, 19 en 20](https://github.com/nl-design-system/kernteam/issues/256#issuecomment-1740455183)

 Formulieren: voeg pagina “Maak het makkelijk” toe

---

docs/richtlijnen/formulieren/03-wees-precies.mdx

voegt “Wees precies” toe en die bevat [formulierfouten 2, 6 en 11](https://github.com/nl-design-system/kernteam/issues/256#issuecomment-1740455183)

Formulieren: voeg pagina “Wees precies” toe

---

docusaurus.config.js

banner-aanpassing

---

docs/project/events/design-systems-week-2023/1-programma.md
docs/project/events/design-systems-week-2023/english/1-program.md
docusaurus.config.js

Dit voegt video's dag 4 (plus: GOV.UK sessie van dag 3) toe. 
Ook een update voor de banner bovenin.

docs: Voeg video's dag 4 toe

---

src/components/SessionTable.module.css
src/components/SessionTable.tsx

Maak de tabel responsive door 'm in een scrollbare div te zetten die niet breder is dan 90% van de viewport. Poor man's responsive table tot we iets beters hebben?

chore: Make tables responsive, the poor man's edition

---

docs/meedoen/als-designer/README.md
docs/meedoen/als-designer/community.md
docs/meedoen/als-designer/figma-structuur.mdx

De linkjes naar de backlog en documentatie repo gefixed.

docs: update backlog en documentatie linkjes

---

docs/project/events/heartbeat.mdx

Not inspired to write a summary for the video, but wanted to have the videos online quickly to share with folks asking for it who missed todays heartbeat.

docs: add 2 heartbeat videos for october

---

docs/meedoen/sidebar.js
docs/richtlijnen/sidebar.js

(nav feedback van Joost van DT TOP)

fix: Use more descriptive titles

---

docs/richtlijnen/formulieren/00-alle-richtlijnen/02-descriptions.mdx
docs/richtlijnen/formulieren/00-alle-richtlijnen/_button-accessible-name.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_button-image.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_button-keyboard.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_description-length.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_description-target-size.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_label-accessible-name-code.mdx
docs/richtlijnen/formulieren/00-alle-richtlijnen/_label-accessible-name.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_label-visible-accessible-name-code.mdx
docs/richtlijnen/formulieren/00-alle-richtlijnen/_label-visible-accessible-name.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_placeholder-colour-contrast.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_placeholder-label.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_question-double.md

- Meer (goede) voorbeelden toegevoegd bij labels
- Onderwerpen in de intro opgesomt bij descriptions
- Wat typos geflixt

Docs feedback dec 23

---

docs/project/events/heartbeat.mdx

docs: add 12 december heartbeat video

---

package-lock.json
package.json
src/theme/Root.js

This fixes the placeholder contrast because of PR https://github.com/nl-design-system/themes/pull/478

build: switch to new Voorbeeld npm package

---

docs/richtlijnen/formulieren/00-alle-richtlijnen/06-questions.mdx
docs/richtlijnen/formulieren/00-alle-richtlijnen/_question-contact.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_question-double-code.mdx
docs/richtlijnen/formulieren/00-alle-richtlijnen/_question-double.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_question-needed.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_question-why.md

Hey Rian en Hidde, ik heb eindelijk kunnen tegenlezen. Ik heb mijn feedback als een pull request neergezet.

Feedback op questions

---

docs/project/over-nlds.mdx
docs/project/wie-doet-mee.mdx
sidebarConfig.ts
src/components/HomepageHero.module.css
src/pages/index.tsx

Deze volgt https://github.com/nl-design-system/documentatie/pull/402 op, nav feedback van @yolijn.
Wat is er anders:
- nieuwe pagina: [Over NL Design System](https://documentatie-git-helderdere-boodschap-nl-design-system.vercel.app/project/over-nlds)
- [homepage](https://documentatie-git-helderdere-boodschap-nl-design-system.vercel.app/) introtekst geupdate en iets meer pakkende heading dan 'NL Design System' 
- stukje 'meedoen kan op allerlei manieren' op [Wie doet mee](https://documentatie-git-helderdere-boodschap-nl-design-system.vercel.app/project/wie-doet-mee) (die we los nog eens goed onder handen gaan nemen, maar voelde als een logische plek om dat te plaatsen)
Opmerkingen
- Ik heb ook de homepage meegenomen, denk dat het zo makkelijk in een elevator tot je te nemen zal zijn, het …

Leg uit wat NLDS is en hoe het werkt (2)

---

docs/project/events/design-systems-week-2023/1-programma.md
docs/project/events/design-systems-week-2023/2-tijdschema-per-dag.md
docs/project/kernteam.mdx

Er stonden nog een paar vermeldingen van ons oude emailadres.

fix: Update email addresses

---

docs/project/kernteam.mdx
src/components/CoreTeam/Hidde.tsx
src/components/CoreTeam/Jeffrey.tsx
src/components/CoreTeam/Peter.tsx
src/components/CoreTeam/Renate.tsx
src/components/CoreTeam/Rian.tsx
src/components/CoreTeam/Robbert.tsx
src/components/CoreTeam/TeamMember.d.ts
src/components/CoreTeam/Yolijn.tsx
src/components/CoreTeam/index.tsx

Docs: improve emails

---

docs/richtlijnen/formulieren/00-alle-richtlijnen/_confirmation-accessibility.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_confirmation-contact.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_confirmation-next-steps-code.mdx
docs/richtlijnen/formulieren/00-alle-richtlijnen/_confirmation-next-steps.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_confirmation-success.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/confirmation.mdx

zoals beschreven in https://github.com/nl-design-system/kernteam/issues/402, zie ook [bijbehorende HackMD](https://hackmd.io/ghKb761hTzW6o5EGEtgxfw?both)

Voeg richtlijn “Bevestigingspagina” toe

---

docs/richtlijnen/tekst-en-taalgebruik.md
docs/wcag/1.1.1.mdx
docs/wcag/_cta_gebruikersonderzoek.md
docs/wcag/_wcag_footer_info.md

Eerste SC 1.1.1 als ondersteuning voor de richtlijnen
related issue: #561

wcag: 1.1.1

---

static/.htaccess

Tighten .htaccess RewriteMatch rules to match from the start of the URL Add quotes to align with the Apache documentation
Fixes #593

fix: .htacccess

---

docs/richtlijnen/formulieren/00-alle-richtlijnen/_description-associated.md
docs/richtlijnen/formulieren/00-alle-richtlijnen/_multistep-location.md

Info over formulierenmodes verplaatst en verduidelijkt.
related issue: #582

Guidelines: reorganise info on meer stappen 

---

docs/richtlijnen/stijl/iconen.md
docs/richtlijnen/stijl/kleuren.md

Documentatie rondom kleur en iconen aangepast na feedback van Aline Nap
https://github.com/nl-design-system/kernteam/issues/534

Stijl richtlijnen update

---

docs/richtlijnen/formulieren/_errors-clarity.md
docs/richtlijnen/formulieren/_errors-description.md
docs/richtlijnen/formulieren/_errors-feedback.md
docs/richtlijnen/formulieren/_errors-no-native.md
docs/richtlijnen/formulieren/_errors-summary.md
docs/wcag/3.3.1.mdx

URL: https://documentatie-git-wcag-3-3-1-foutidentificatie-nl-design-system.vercel.app/wcag/3.3.1

WCAG-pagina 3.3.1 Foutidentificatie

---

docs/wcag/3.3.4.mdx

URL: https://documentatie-git-wcag-334-foutpreventie-e29d30-nl-design-system.vercel.app/wcag/3.3.4
Issue: https://github.com/nl-design-system/documentatie/issues/673

WCAG-pagina 3.3.4 Foutpreventie (wettelijk, financieel, gegevens)

---

blog/2024/20240305-meerdere-manieren-contact.md

fixes https://github.com/nl-design-system/documentatie/issues/618
Preview van de post: https://documentatie-git-add-meerdere-manieren-post-nl-design-system.vercel.app/blog/meerdere-manieren-contact

Plaats blog post “Ik wil je wat vragen, maar ik heb geen WhatsApp!”

---

docs/richtlijnen/formulieren/_help-error-prevention.md
docs/richtlijnen/formulieren/help-the-user.mdx

URL: https://documentatie-git-guidelines-add-error-p-e23b5b-nl-design-system.vercel.app/richtlijnen/formulieren/voorkom-fouten
Issue: https://github.com/nl-design-system/documentatie/issues/691

Guidelines: Voegt RL over foutpreventie toe aan pagina Voorkom fouten

---

docs/voorbeelden/patronen/formulieren/_research-info.mdx

Verwijzing naar het formulier bij Gemeente Voorbeeld klopte niet meer. Aangepast.

Update link research info

---

docs/wcag/4.1.3.mdx

SC 4.1.3 Statusberichten
Related issue: https://github.com/nl-design-system/documentatie/issues/675
URL: https://documentatie-git-wcag-4-1-3-statusberichten-nl-design-system.vercel.app/wcag/4.1.3

WCAG-pagina 4.1.3 Statusberichten

---

docs/community/events/heartbeat/videos.mdx

docs: voeg video toe

---

docs/componenten/definition-of-done.mdx

Resolves nl-design-system/backlog#148

feat: component dod in line with Miro

---

docs/richtlijnen/introductie.md

Related issue en discussie: https://github.com/nl-design-system/documentatie/issues/742
URL: https://documentatie-git-guidelines-improve-intro-page-nl-design-system.vercel.app/richtlijnen/introductie

Richtlijnen: Verbeteren intropagina richtlijnen

---

docs/voorbeelden/patronen/formulieren/_research-info.mdx
docs/voorbeelden/patronen/formulieren/bevestigingspagina.mdx
docs/voorbeelden/patronen/formulieren/controlepagina.mdx
docs/voorbeelden/patronen/formulieren/foutmeldingen.mdx
docs/voorbeelden/patronen/formulieren/funnel-header.mdx
docs/voorbeelden/patronen/formulieren/inloggen.mdx
docs/voorbeelden/patronen/formulieren/intropagina.mdx
docs/voorbeelden/patronen/formulieren/meerstappenformulier.mdx
docs/voorbeelden/patronen/formulieren/niet-verplichte-velden.mdx
docs/voorbeelden/patronen/formulieren/opslaan-of-stoppen.mdx
docs/voorbeelden/patronen/formulieren/responsive-design.mdx
docs/voorbeelden/patronen/formulieren/stapelen-en-uitlijnen.mdx
docs/voorbeelden/patronen/formulieren/startpunt.mdx
docs/voorbeelden/patronen/formulieren/terug-navigeren.mdx
docs/voorbeelden/patronen/formulieren/uploaden.mdx
docs/voorbeelden/patronen/formulieren/visual-design.mdx
docs/voorbeelden/patronen/formulieren/volgende-stap.mdx
docs/voorbeelden/patronen/formulieren/voortgang-indicatie.mdx

Crosslinken van patronen naar gerelateerde richtlijnen van het NL Design System.

Patronen: crosslinken naar richtlijnen

---

docs/richtlijnen/formulieren/README.mdx
docs/richtlijnen/stijl/README.md
docs/wcag/0-introduction.mdx
sidebarConfig.ts

Gerelateerd issue: #829 
URL: https://documentatie-git-wcag-intro-page-nl-design-system.vercel.app/wcag/introduction

WCAG-pagina's: Introductiepagina toevoegen

---

docs/componenten/_help-wanted-stappenplan.mdx

Help Wanted stappenplan openbaar zodat kernteam en community leden deze kunnen volgen.

Help Wanted stappenplan

---

docs/wcag/2.4.4.mdx

URL: https://documentatie-git-wcag-2-4-4-linkdoel-nl-design-system.vercel.app/wcag/2.4.4

WCAG-pagina: 2.4.4 Linkdoel (in context)

---

docs/richtlijnen/formulieren/_confirmation-accessibility.md
docs/richtlijnen/formulieren/_errors-feedback.md
docs/richtlijnen/formulieren/_multistep-step-count.md
docs/wcag/0-introduction.mdx
docs/wcag/2.4.2.mdx

Issue: #655
URL: https://documentatie-git-wcag-2-4-2-paginatitel-nl-design-system.vercel.app/wcag/2.4.2

WCAG-pagina: 2.4.2 Paginatitle

---

docs/community/events/estafettemodeldag.mdx

Ik had een foutje gemaakt. 
thanks @Rozerinay !

docs: fix broken title

---

docs/community/events/design-open-dag.mdx

open-dag-update

---

docs/richtlijnen/formulieren/_button-accessible-name.md
docs/richtlijnen/formulieren/_label-accessible-name.md
docs/richtlijnen/formulieren/_when-which-compat.md
docs/wcag/4.1.2.mdx
packages/nlds-design-tokens/package.json

Issue: https://github.com/nl-design-system/documentatie/issues/674
URL: https://documentatie-git-wcag-412-naam-rol-waarde-nl-design-system.vercel.app/wcag/4.1.2/
Eerste SC met veelgemaakte fouten erbij.

WCAG-pagina 4.1.2 naam rol waarde

---

docs/community/sluit-je-aan-success.mdx
docs/community/sluit-je-aan.mdx
sidebarConfig.ts
src/components/NewsletterSignUp.tsx
src/css/custom.css

dit PR maakt:
- nieuwe pagina “Sluit je aan”
- aanmeldformulier om je gegevens achter te laten als communitylid
- veld om interesse te peilen op basis van één of meer predefind keuzes
- freeform veld om aan te geven waar men mee bezig is

docs: voeg community signup toe

---

docs/wcag/0-introduction.mdx
docs/wcag/3.1.1.mdx

Related issue: #665 
Preview: https://documentatie-git-wcag-3-1-1-taal-pagina-nl-design-system.vercel.app/wcag/3.1.1

WCAG-pagina 3.1.1 Taal van de pagina

---

sidebarConfig.ts

Maak “Sluit je aan” het eerste item onder “Community”

---

blog/2024/20240522-community-blocks.md

gelieve deze eerst te mergen https://github.com/nl-design-system/documentatie/pull/947/ zodat de afbeelding waar we hier naar linken bestaat

voeg post over community blocks toe

---

.github/workflows/cd.yml

This reverts commit 833eaf0975e6e0bbc1f1a29e0ce6e8234e5d6b94.

Revert "build: use actions/deploy-pages for GH Pages"

---

package.json
packages/nlds-design-tokens/src/tokens.json
pnpm-lock.yaml

style: inherit code font-size, do not hardcode

---

docs/handboek/help-wanted-stappenplan.mdx

Een stuk in de aankondiging die we doen in Slack, ontbrak.

docs: onvolledige zin aangevuld

---

package.json
pnpm-lock.yaml
src/_generate-component-pages/component-page.ts
src/_generate-component-pages/index.ts
src/components/TaskList.module.css
src/components/TaskList.tsx
src/utils.ts
tsconfig.commonjs.json

feat: add component status progress

---

docs/wcag/0-introduction.mdx
docs/wcag/2.4.10.mdx

Related issue: #938 
Preview: https://documentatie-git-wcag-2-4-10-paragraafkoppen-nl-design-system.vercel.app/wcag/2.4.10

WCAG-pagina 2.4.10 Paragraafkoppen

---

docs/handboek/help-wanted-stappenplan.mdx

Nog een paar 'het' naar 'de' voor het Help Wanted stappenplan.

Het-naar-de

---

docs/handboek/organisatie/vragen-over-aanbestedingen.md

Vet, deze nieuwe pagina's! 
Ik had twee verbeterpuntjes: 
- vraagtekens achter alle vragen
- 'gemeenten' -> 'organisatie', want gemeente is maar 1 van de organisatietypes? (en enkelvoud want vraag zou vast komne uit één specifieke organisatie)

Tweak de headings een beetje

---

blog/2024/20240624-toegankelijke-foutmeldingen.md

Issue: https://github.com/nl-design-system/documentatie/issues/613
Preview: https://documentatie-git-blog-post-foutmeldingen-nl-design-system.vercel.app/blog/toegankelijke-foutmeldingen-formulieren

Blogpost: Toegankelijke foutmeldingen in formulieren

---

docusaurus.config.ts

chore: remove borrel announcement

---

blog/2024/20240624-toegankelijke-foutmeldingen.md

(want dit hebben we in gebruikersonderzoek gezien)

Leg uit dat contactinfo in footer wel een slim idee is

---

docs/project/links.mdx

https://documentatie-git-docs-design-system-links-nl-design-system.vercel.app/project/links

docs: reorganise and extend links to other design systems

---

docs/handboek/organisatie/meedoen.md

nav [Robberts comment in #1063](https://github.com/nl-design-system/documentatie/pull/1063#pullrequestreview-2150103937)

docs: voeg uitleg over snowflake toe

---

docs/componenten/spinner/index.mdx

Meer in lijn gebracht met onze overige documentatie.

Description Spinner aangepast

---

src/components/ComponentOverview.module.css
src/components/ComponentOverview.tsx
src/components/ComponentPage.module.css
src/components/ComponentPage.tsx
src/css/custom.css
src/utils.ts

feat: add component filter

---

docs/handboek/component-bijdragen/hall-of-fame-stappenplan.mdx

De stap 'Hall of Fame' staat nu aan het einde.

Volgorde Hall of Fame item in sidebar gewijzigd

---

docs/community/events/heartbeat/videos.mdx

https://documentatie-git-docs-heartbeats-nl-design-system.vercel.app/events/heartbeat/videos#geen-video

docs: heartbeat history

---

docs/footer/privacyverklaring.md

Had er nog twee gemist, hiermee wordt het consistenter, dank voor het spotten Roos!

Maak gebruik “u” en “je” consistent

---

docs/community/events/design-open-hour/design-open-hour.mdx
docs/community/events/developer-open-hour/developer-open-hour.mdx

Linkje naar Slack kanalen gefixed.

fix-slack-link

---

docs/componenten/definition-list/index.mdx
static/.htaccess

Zorgt ervoor dat 'Definition list' wordt omgezet naar 'Description list' in de documentatie.

Definition to description list in documentation

---

package.json
pnpm-lock.yaml

button, headings and lists now community

build: update component-progress

---

src/components/ComponentOverview.module.css
src/components/ComponentOverview.tsx
src/design-tokens.d.ts
tsconfig.json

to explain "show available components"

docs: add filter component notice

---

docs/handboek/designer/community.md
docs/project/links.mdx

docs: add MinVenJ design system

---

docs/community/events/design-systems-week-2024/programma.md
docs/community/events/design-systems-week-2024/speakers.json

(al ok van Lotte)
Preview: https://documentatie-git-add-lotte-nl-design-system.vercel.app/events/design-systems-week-2024/programma

chore: add Lotte

---

.changeset/focus-volgorde-pagina.md
docs/wcag/2.4.03.mdx

Issue: #656 
Preview: https://documentatie-git-wcag-243-focus-volgorde-nl-design-system.vercel.app/wcag/2.4.3

WCAG-pagina: 2.4.3 focus volgorde, tekst toegevoegd

---

lint-staged.config.cjs

Make sure Prettier ignores files that it does not have a parser for

fix: lint-staged

---

.changeset/wcag-1.2.9-changelog.md
docs/wcag/1.2.09.mdx
docs/wcag/summaries/_1.2.9-summary.md

Issue: https://github.com/nl-design-system/documentatie/issues/1304
Dit is een samenvatting voor niet technische personen, meer het 'wat' en 'waarom'.
Pas bij de volledige uitleg kom precies het 'hoe'.

WCAG-pagina's: 1.2.9 Louter-geluid (live) summary

---

docs/community/wie-doet-mee.mdx
src/components/CardGroup.module.css
src/pages/index.tsx

docs: improve wie doet er mee page

---

docs/community/community-sprints.mdx
sidebarConfig.ts

docs: add community sprints

---

docs/componenten/paragraph/_guidelines.md
docs/richtlijnen/formulieren/visual-design/2-text-contrast/_guideline.md
docs/richtlijnen/formulieren/visual-design/3-placeholder-contrast/_guideline.md
docs/richtlijnen/stijl/kleuren.md
docs/wcag/1.4.06.mdx
docs/wcag/summaries/_1.4.3-summary.md
docs/wcag/summaries/_1.4.6-summary.md

Gerelateerd issue: #1304
Preview: https://documentatie-git-wcag-146-summary-nl-design-system.vercel.app/wcag/1.4.6
Plus aanpassing tekst van 1.4.3 summary voor consistentie.

WCAG-pagina 1.4.6 Contrast (versterkt) summary

---

static/factsheets/managers/index.html

goede tip van @emma-koole
voorbeeldje: https://documentatie-git-fix-add-link-to-faq-nl-design-system.vercel.app/factsheets/managers

Voeg linkje naar veelgestelde vragen toe

---

docs/community/events/design-systems-week-2024/programma.md
docs/community/events/design-systems-week-2024/speakers.json
docs/community/events/design-systems-week-2024/tijdschema-per-dag.md

We misten nog specifieke info van de lightning talks tijdens de speciale Design Systems Week Heartbeat, deze voegt dat toe

Add more info on Design Systems Week Heartbeat

---

docs/componenten/code-block/index.mdx
docs/componenten/code/index.mdx
docs/componenten/color-sample/index.mdx
docs/componenten/login-link/index.mdx
docs/componenten/mark/index.mdx
docs/componenten/subscript/index.mdx
docs/componenten/superscript/index.mdx
package.json
pnpm-lock.yaml
static/svg/componenten_overzicht_alert-dialog.svg
static/svg/componenten_overzicht_code-block.svg
static/svg/componenten_overzicht_code.svg
static/svg/componenten_overzicht_color-sample.svg
static/svg/componenten_overzicht_login-link.svg
static/svg/componenten_overzicht_mark.svg
static/svg/componenten_overzicht_subscript.svg
static/svg/componenten_overzicht_superscript.svg

feat: add help wanted components

---

.changeset/wcag-2.2.3-summary.md
docs/wcag/2.2.03.mdx
docs/wcag/summaries/_2.2.3-summary.md

WCAG-pagina's: 2.2.3  Geen timing - summary

---

.changeset/wcag-1.4.7-summary.md
docs/wcag/1.4.07.mdx
docs/wcag/summaries/_1.4.7-summary.md

Gerelateerd: #1304
Preview: https://documentatie-git-wcag-147-summary-nl-design-system.vercel.app/wcag/1.4.7

WCAG-pagina's: 1.4.7 Weinig of geen achtergrondgeluid - summary

---

.changeset/wcag-1.4.9-summary.md
docs/wcag/1.4.09.mdx
docs/wcag/summaries/_1.4.9-summary.md

Gerelateerd: #1304
Preview: https://documentatie-git-wcag-149-summary-nl-design-system.vercel.app/wcag/1.4.9

WCAG-pagina's: 1.4.9 Afbeeldingen van tekst (geen uitzondering) - summary

---

docs/componenten/spinner/index.mdx
docs/componenten/tabs/index.mdx
docs/componenten/toggletip/index.mdx
docs/project/faq.mdx
docs/project/over-nl-design-system.mdx
docs/richtlijnen/_tekst-en-taalgebruik/tekst-en-taalgebruik.md
docs/richtlijnen/formulieren/button/3-placement/_guideline.md
docs/richtlijnen/formulieren/link/3-in-new-tab/_guideline.md
docs/richtlijnen/formulieren/placeholder/2-search/_code.mdx
docs/richtlijnen/formulieren/visual-design/7-no-image-buttons/_guideline.md
docs/richtlijnen/formulieren/visual-design/8-order/_guideline.md
docs/richtlijnen/formulieren/visual-design/README.mdx
docs/richtlijnen/stijl/kleuren.md
docs/voorbeelden/patronen/formulieren/foutmeldingen.mdx
docs/wcag/2.1.01.mdx
docs/wcag/2.5.05.mdx
docs/wcag/3.2.01.mdx
docs/wcag/summaries/_1.4.12-summary.md
docs/wcag/summaries/_1.4.8-summary.md
docs/wcag/summaries/_2.1.4-summary.md

Gerelateerde issues #1335 en #1220.

Docs: De tekst knop overal aangepast naar button

---

docs/wcag/summaries/_1.3.4-summary.md

WCAG-pagina's: fix typo in WCAG 1.3.4

---

docs/wcag/summaries/_1.3.3-summary.md

WCAG-pagina's: fix typo in WCAG 1.3.3

---

.changeset/wcag-2.2.4-summary.md
docs/wcag/2.2.03.mdx
docs/wcag/2.2.04.mdx
docs/wcag/summaries/_2.2.4-summary.md

Gerelateerd issue: #1304 
Perview: https://documentatie-git-wcag-224-summary-nl-design-system.vercel.app/wcag/2.2.4

WCAG-pagina's 2.2.4 Onderbrekingen - summary

---

.changeset/wcag-2.1.3-summary.md
docs/wcag/2.1.03.mdx
docs/wcag/summaries/_2.1.1-summary.md
docs/wcag/summaries/_2.1.3-summary.md

Gerelateerd issue: #1304
Preview: https://documentatie-git-wcag-wcag-2-1-3-summary-nl-design-system.vercel.app/wcag/2.1.3

WCAG-pagina's: 2.1.3 Toetsenbord (geen uitzondering) - summary

---

docs/project/links.mdx

volgens [Stijl van UWV](https://www.uwv.nl/nl/over-uwv/pers/stijl-van-uwv) is dit nu de URL

docs: update link

---

docs/community/events/design-systems-week-2024/programma.md

voeg omschrijving van Bart's presentatie toe aan de site

docs: voeg omschrijving Bart toe

---

docs/componenten/button/_wcag-1.1.1.md
docs/componenten/button/_wcag-1.4.11.md
docs/componenten/button/_wcag-1.4.12.md
docs/componenten/button/_wcag-1.4.3.md
docs/componenten/button/_wcag-1.4.4.md
docs/componenten/button/_wcag-1.4.5.md
docs/componenten/button/_wcag-2.1.1.md
docs/componenten/button/_wcag-2.4.13.md
docs/componenten/button/_wcag-2.4.6.md
docs/componenten/button/_wcag-2.4.7.md
docs/componenten/button/_wcag-2.5.2.md
docs/componenten/button/_wcag-2.5.3.md
docs/componenten/button/_wcag-2.5.5.md
docs/componenten/button/_wcag-3.1.2.md
docs/componenten/button/_wcag-3.2.4.md
docs/componenten/button/_wcag-4.1.2.md
docs/componenten/button/index.mdx
src/components/TaskList.tsx
src/components/WcagList.tsx
src/components/wcag21.ts
src/components/wcag22.ts

Preview: kopje "Acceptatiecriteria" van "Button"
https://documentatie-git-docs-component-wcag-criteria-nl-design-system.vercel.app/button/#acceptatiecriteria

docs: add WCAG successcriteria for a component

---

docs/voorbeelden/patronen/formulieren/niet-verplichte-velden.mdx
docs/voorbeelden/patronen/formulieren/voortgang-indicatie.mdx

Laatste stuk tekst aanpassen: zie #1220

docs: Aanpassen tekst patronen voor richtlijnen.

---

.changeset/wcag-3.3.5-summary.md
docs/wcag/3.3.05.mdx
docs/wcag/summaries/_3.3.5-summary.md

Voegt pagina met samenvatting "3.3.5 Hulp" toe.
Preview: https://documentatie-git-docs-wcag-335-summary-nl-design-system.vercel.app/wcag/3.3.5

docs: WCAG 3.3.5 Hulp - summary

---

.changeset/wcag-3.3.9-summary.md
docs/wcag/3.3.09.mdx
docs/wcag/summaries/_3.3.9-summary.md

Voegt pagina met samenvatting "3.3.9 Toegankelijke authenticatie (uitgebreid)" toe.
Preview: https://documentatie-git-docs-wcag-339-summary-nl-design-system.vercel.app/wcag/3.3.9

docs: WCAG 3.3.9 Toegankelijke authenticatie (uitgebreid)

---

.changeset/wcag-3.2.5-summary.md
docs/wcag/3.2.05.mdx
docs/wcag/summaries/_3.2.5-summary.md

Voegt pagina met samenvatting "3.2.5 Verandering op verzoek" toe.
Preview: https://documentatie-git-docs-wcag-325-summary-nl-design-system.vercel.app/wcag/3.2.5

docs: WCAG 3.2.5 Verandering op verzoek - summary

---

docs/community/events/design-systems-week-2024/programma.md
docs/community/events/design-systems-week-2024/speakers.json
docs/community/events/design-systems-week-2024/tijdschema-per-dag.md

~(nog in afwachting van feedback)~
✅  ok bevonden
deze PR fixt ook verkeerd aangegeven tijden

Voeg de info van Thijs toe

---

.changeset/wcag-2.3.3-summary.md
docs/wcag/2.3.03.mdx
docs/wcag/summaries/_2.3.3-summary.md

Voegt pagina met samenvatting WCAG-pagina 2.3.3 Animatie uit interacties toe.
Gerelateerd issue #1304 
Preview: https://documentatie-git-docs-wcag-233-summary-nl-design-system.vercel.app/wcag/2.3.3

docs: WCAG 2.3.3 Animatie uit interacties - summary

---

.changeset/wcag-2.2.5-summary.md
docs/wcag/2.2.05.mdx
docs/wcag/summaries/_2.2.5-summary.md

Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/1304
Preview: https://documentatie-git-docs-wcag-225-summary-nl-design-system.vercel.app/wcag/2.2.5
Vervangt PR: https://github.com/nl-design-system/documentatie/pull/1412

docs: WCAG 2.2.5 Herauthentisering - summary

---

.changeset/wcag-2.2.6-summary.md
docs/wcag/2.2.06.mdx
docs/wcag/summaries/_2.2.6-summary.md

Gerelateerd issue: #1304
Preview: https://documentatie-git-docs-wcag-226-summary-nl-design-system.vercel.app/wcag/2.2.6/

docs: WCAG 2.2.6 Time-outs - summary

---

docs/componenten/button/_wcag-1.1.1.md
docs/componenten/button/_wcag-1.4.12.md
docs/componenten/button/_wcag-1.4.3.md
docs/componenten/button/_wcag-1.4.4.md
docs/componenten/button/_wcag-2.4.13.md
docs/componenten/button/_wcag-2.4.7.md
docs/componenten/button/_wcag-2.5.2.md
docs/componenten/button/_wcag-2.5.3.md
docs/componenten/button/_wcag-2.5.5.md
docs/componenten/button/_wcag-4.1.2.md

Tekstaanpassingen na overleg met het team. Gerelateerd issue: #1392 
Preview: https://documentatie-git-docs-component-button-b72c3c-nl-design-system.vercel.app/button

docs: aanpassen tekst 4.1.2 voor component button

---

.changeset/wcag-3.1.4-summary.md
docs/wcag/3.1.02.mdx
docs/wcag/3.1.04.mdx
docs/wcag/summaries/_3.1.4-summary.md

Voegt pagina met samenvatting "3.1.4 Afkortingen" toe.
Preview: https://documentatie-git-docs-wcag-314-summary-nl-design-system.vercel.app/wcag/3.1.4

docs: wcag 3.1.4 Afkortingen - summary

---

.changeset/wcag-3.1.6-summary.md
docs/wcag/3.1.06.mdx
docs/wcag/summaries/_3.1.6-summary.md

Voegt pagina met samenvatting "3.1.6 Uitspraak" toe.
Preview: https://documentatie-git-docs-wcag-316-summary-nl-design-system.vercel.app/wcag/3.1.6

docs: WCAG 3.1.6 Uitspraak - summary

---

.changeset/wcag-3.1.5-summary.md
docs/wcag/3.1.05.mdx
docs/wcag/summaries/_3.1.5-summary.md

Voegt pagina met samenvatting "3.1.5 Leesniveau" toe.
Preview: https://documentatie-git-docs-wcag-315-summary-nl-design-system.vercel.app/wcag/3.1.5

docs: wcag 3.1.5 Leesniveau - summary

---

docs/project/links.mdx

Link aangepast van het Figma ROOS RVO Design System.

chore: link aangepast

---

docusaurus.config.ts

chore: update banner

---

docs/wcag/1.4.03.mdx

Gerelateerd: #1408 en #642
Preview:
https://documentatie-git-docs-wcag-143-nl-design-system.vercel.app/wcag/1.4.3
Deze PR maakt de [WCAG-pagina Succescriterium 1.4.3 Contrast (minimum)](https://nldesignsystem.nl/wcag/1.4.3) helemaal af.

docs: WCAG-pagina 1.4.3

---

docusaurus.config.ts

docs: remove design systems week 2024 banner

---

package.json
pnpm-lock.yaml

This PR will update the component progress to version 70.

build: update component progress to 70

---

docs/componenten/button/index.mdx
src/components/ComponentCriteriaList.module.css
src/components/ComponentCriteriaList.tsx

De accepratiecriteria zijn nu gesorteerd op soort test en in een details/summery verzameld.
Graag inhoudelijke discussies bij het gerelateerde issue: #1548
Preview: https://documentatie-git-chore-components-refactor-ac-nl-design-system.vercel.app/button

chore: Refactor component acceptatiecriteria, voor de button, maar om over te nemen voor alle componenten

---

docs/richtlijnen/stijl/typography/4-font/_guideline.md
docs/richtlijnen/stijl/typography/5-markup/_guideline.md

- Updated guideline for lettercontrast.
- Updated and added links to fonts.
- Changed 'Kopjes' to 'Koppen'.

Docs: update typography guidelines

---

package.json
pnpm-lock.yaml

This PR will update the component progress to version 72.

build: @nl-design-system/component-progress

---

.changeset/ac-login-link.md
docs/componenten/ac/_wcag-2.1.1-link.md
docs/componenten/ac/_wcag-2.5.3-link.md
docs/componenten/ac/_wcag-4.1.2-link.md
docs/componenten/login-link/_wcag-1.1.1.md
docs/componenten/login-link/_wcag-3.2.4.md
docs/componenten/login-link/index.mdx

Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/1595

docs: Acceptatiecriteria component Login Link

---

docs/handboek/component-bijdragen/community-stappenplan/voor-kernteam.mdx
docs/handboek/component-bijdragen/definition-of-done.mdx
docs/handboek/component-bijdragen/help-wanted-stappenplan.mdx

Updated Help Wanted and Community documentation.

docs: update help wanted and community documentation

---

docs/componenten/link/_wcag-1.1.1.md
docs/componenten/link/_wcag-3.2.4.md
docs/componenten/link/index.mdx

Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/1375
Preview: https://documentatie-git-docs-acceptatiecriteria-link-nl-design-system.vercel.app/link

docs: Acceptatiecriteria component Link

---

docs/componenten/data-badge/_wcag-1.1.1-data-badge.md
docs/componenten/data-badge/_wcag-1.3.1-data-badge.md
docs/componenten/data-badge/_wcag-1.4.1-data-badge.md
docs/componenten/data-badge/index.mdx

Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/1375

docs: Acceptatiecriteria Data Badge

---

src/components/BreadcrumbNav.tsx

fixes https://github.com/nl-design-system/documentatie/issues/418

fix: add label to breadcrumb

---

.github/workflows/cd.yml

fixes missing htaccess
https://github.com/actions/upload-artifact/commit/cb6558bb10fe4afe4054d0be4b3136e673eb5e7f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R114

build: fix add hidden files to build artifact

---

docs/componenten/data-badge/index.mdx

Voegt sectie zoom en herschalen van tekst toe

docs: toevoegen 1.4.4 en 1.4.12 aan component Number Badge

---

package.json
pnpm-lock.yaml

This PR will update the component progress to version 75.

build: update component progress to 75

---

.changeset/ac-color-sample.md
docs/componenten/ac/_wcag-1.3.1-heading.md
docs/componenten/ac/_wcag-1.4.5.md
docs/componenten/ac/_wcag-2.4.6-heading.md
docs/componenten/ac/_wcag-4.1.1-heading.md
docs/componenten/color-sample/_wcag-1.1.1.md
docs/componenten/color-sample/_wcag-1.3.1.md
docs/componenten/color-sample/_wcag-1.3.2.md
docs/componenten/color-sample/_wcag-1.4.11.md
docs/componenten/color-sample/_wcag-1.4.5.md
docs/componenten/color-sample/index.mdx
docs/richtlijnen/formulieren/visual-design/8-order/_guideline.md

docs: Accepatiecriteria color sample

---

package.json
pnpm-lock.yaml

chore: bump @nl-design-system/component-progress

---

.changeset/ac-code-block.md
docs/componenten/ac/_wcag-1.4.11-code.md
docs/componenten/code-block/_wcag-1.3.1.md
docs/componenten/code-block/index.mdx

Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/1375

docs: Accepatiecriteria component Code Block

---

.changeset/ac-mark.md
docs/componenten/data-badge/_wcag-1.3.1-data-badge.md
docs/componenten/data-badge/_wcag-1.4.1-data-badge.md
docs/componenten/link/_wcag-3.2.4.md
docs/componenten/mark/_wcag-1.3.1.md
docs/componenten/mark/_wcag-1.4.11.md
docs/componenten/mark/index.mdx
docs/componenten/number-badge/_wcag-1.3.1-number-badge.md

Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/1375

Docs: Acceptatiecriteria bij component mark

---

docs/componenten/ac/_wcag-2.5.5.md
docs/wcag/summaries/_2.5.5-summary.md

docs: uitzondering erbij voor linktekst WCAG 2.5.5

---

src/components/ComponentPage.tsx

Kleine tekstaanpassing: Verander `We vinden het belangrijk dat` naar `We vinden het belangrijk dat de component `
Preview: https://documentatie-git-docs-tekstaanpassing-h-9a7dae-nl-design-system.vercel.app/accordion

docs: toevoegen tekst: de component

---

src/components/CodeBlockSyntaxHighlighting.tsx

fixes https://github.com/nl-design-system/documentatie/issues/1725

Use tabindex 0 on code block component

---

docs/wcag/1.1.01.mdx

Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/1529
Preview: https://documentatie-git-docs-text-changes-wcag-111-nl-design-system.vercel.app/wcag/1.1.1

docs: WCAG-pagina 1.1.1, aanpassingen na review Joost van der Steen

---

docs/wcag/summaries/_3.2.1-summary.md

Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/1645

docs: WCAG-pagina 3.2.1 Contextwijziging, toevoegen focuswijziging

---

docs/componenten/button/index.mdx
docs/componenten/link/index.mdx
docs/componenten/login-link/index.mdx

2.4.11 vergeten toe te voegen aan enkele componenten.

docs: toevoegen 2.4.11 aan acceptatiecriteria componenten

---

src/components/NewsletterSignUp.tsx

fixes https://github.com/nl-design-system/documentatie/issues/1746

docs: label not required field as not required

---

package.json
pnpm-lock.yaml

This PR will update the component progress to version 76.

build: update component progress to 76

---

package.json
pnpm-lock.yaml

[<img width="715" alt="Screenshot 2024-11-27 at 20 23 31" src="https://github.com/user-attachments/assets/cef58659-9720-4db0-a23b-88ba189e7426">
](https://documentatie-git-build-update-index-nl-design-system.vercel.app/paragraph)

build: update component index

---

docs/community/events/design-open-hour/design-open-hour.mdx
docs/community/events/design-systems-week-2024/english/index.mdx
docs/community/events/design-systems-week-2024/index.mdx
docs/community/events/developer-open-hour/developer-open-hour.mdx
docs/community/events/heartbeat/heartbeat.mdx
src/components/BreadcrumbNav.tsx
src/components/Breadcrumbs.tsx
src/components/ButtonLink.tsx
src/components/ComponentCard.tsx
src/components/DSWSession.tsx
src/components/HomepageHero.tsx
src/components/Link.tsx
src/pages/bingo/index.tsx
src/pages/index.tsx
src/theme/BlogPostItems/index.tsx
src/theme/DocCard/index.tsx
src/theme/DocSidebarItem/Category/index.tsx
src/theme/DocSidebarItem/Link/index.tsx
src/theme/Footer/LinkItem/index.tsx
src/theme/Footer/Logo/index.tsx
src/theme/Logo/index.tsx
src/theme/NavbarItem/NavbarNavLink.tsx
src/theme/SearchBar/index.tsx

En het leuke is: eindelijk is de focus ring van de link veel meer consistent :)

refactor: do not use DocusaurusLink directly

---

docs/footer/wcag-em-rapport-2024.md

Aangepast:
- 34 Voldoende (inp 33)
- 1 Onvoldoende (ipv 1)

docs: Gerapporteerd over 50 van 50 SC updaten

---

src/components/AnatomyList.css
src/components/AnatomyList.tsx
src/components/ComponentAnatomy.tsx
src/components/Markdown.tsx

feat: add anatomy list

---

src/components/ComponentCriteriaList.css
src/components/ComponentCriteriaList.tsx

Feedback van Joerie: logischer als de details een accordion is

refactor: use Accordion instead of details

---

docs/componenten/ac/_wcag-2.4.13.md
docs/componenten/ac/_wcag-2.4.7-skip-link.md
docs/componenten/ac/_wcag-2.4.7.md
docs/richtlijnen/formulieren/button/4-text/_guideline.md
docs/richtlijnen/formulieren/visual-design/4-focus-visible/README.mdx
docs/richtlijnen/formulieren/visual-design/4-focus-visible/_guideline.md
docs/richtlijnen/formulieren/visual-design/5-field-size/_guideline.md
docs/richtlijnen/stijl/icons/6-colour-contrast/_guideline.md
docs/wcag/2.4.03.mdx
docs/wcag/2.4.13.mdx
docs/wcag/3.2.01.mdx
docs/wcag/3.2.04.mdx
docs/wcag/summaries/_2.5.2-summary.md

Fix typos and spelling

---

docs/componenten/heading/_usage.md

- Add React with CSS example
- Update headings for level 4,5,6

docs: update React examples

---

package.json
pnpm-lock.yaml

This PR will update the component progress to version 95.

build: update component progress 95

---

docs/community/events/design-open-dag.mdx

Update van Open Dag planning voor februari en maart.

Update van Open Dag planning

---

docs/community/events/heartbeat/videos.mdx

Excluding video PNKkFOylpRE which is a snippet of the video zzsKvrlt5Lc.

docs: add heartbeat from jan and feb 2025

---

.changeset/wcag-1.3.3-full-page.md
.changeset/wcag-1.4.1-full-page.md
docs/wcag/1.3.03.mdx
docs/wcag/1.4.01.mdx
docs/wcag/3.3.06.mdx

Gerelateerd: #637 
Preview: https://documentatie-git-docs-637-wcag-133-full-nl-design-system.vercel.app/wcag/1.3.3

docs: WCAG-pagina 1.3.3 Zintuiglijke eigenschappen, volledige pagina

---

blog/2025/20250125-stappen-a-status-website.md

Gerelateerd issue: https://github.com/nl-design-system/documentatie/issues/1219
Preview:https://documentatie-git-blog-blogpost-9-steps-nl-design-system.vercel.app/blog/tips-9-stappen-A-status-website
TL;DR
> Stappenplan voor de ontwikkeling van een toegankelijk webproject met het NL Design System.
> We nemen je aan de hand mee in het hele proces van begin tot eind, en vertellen je hoe het NL Design Systeem in combinatie met de richtlijnen voor toegankelijkheid je hierbij kan helpen.

blog: Blogpost "Haal in één keer de A-status voor je website in 9 stappen"

---

package.json
pnpm-lock.yaml

per request of Amsterdam who updated their documentation of some community components

chore: update component progress to 1.0.1-alpha.101

---

blog/2025/20250125-stappen-a-status-website.md
blog/2025/20250211-a11y-name-link-logo-header.md
docs/wcag/README.mdx

Wat typo's en dubbele tekst aangepast.
De opmerking over het kleurcontrast verwijderd bij de 9 stappen blogpost na overleg met Jues Ernst.

docs: kleine tekstuele aanpassingen na review

---

.changeset/ac-accordion.md
docs/componenten/ac/_wcag-1.1.1-accordion.md
docs/componenten/ac/_wcag-1.3.1-accordion.md
docs/componenten/ac/_wcag-1.4.1-accordion.md
docs/componenten/ac/_wcag-1.4.11-accordion.md
docs/componenten/ac/_wcag-1.4.13-accordion.md
docs/componenten/ac/_wcag-1.4.3-accordion.md
docs/componenten/ac/_wcag-1.4.4-accordion.md
docs/componenten/ac/_wcag-1.4.5-accordion.md
docs/componenten/ac/_wcag-2.1.1-accordion.md
docs/componenten/ac/_wcag-2.4.3-accordion.md
docs/componenten/ac/_wcag-2.4.6-accordion.md
docs/componenten/ac/_wcag-2.5.2-accordion.md
docs/componenten/ac/_wcag-2.5.2.md
docs/componenten/ac/_wcag-2.5.3-accordion.md
docs/componenten/ac/_wcag-2.5.5-accordion.md
docs/componenten/ac/_wcag-3.2.1-accordion.md
docs/componenten/ac/_wcag-3.2.2-accordion.md
docs/componenten/ac/_wcag-4.1.2-accordion.md
docs/componenten/accordion/index.mdx

Gerelateerd issue: [#1437 ](https://github.com/nl-design-system/documentatie/issues/1437)
Preview: https://documentatie-git-docs-ac-accordion-nl-design-system.vercel.app/accordion#acceptatiecriteria

Acceptatiecriteria bij component Accordion

---

docs/componenten/logo/index.mdx
package.json
pnpm-lock.yaml
static/svg/componenten_overzicht_logo.svg

- add illustration for logo.
- add documentation page for logo.
- update component progress.

docs: add logo to documentation site

---

docs/handboek/component-bijdragen/help-wanted-stappenplan.mdx

- Fix typo: extentie → extensie. 
- Add instructions for opening SVG code in text editor.

fix: update help wanted stappenplan

---

package.json
pnpm-lock.yaml

Er waren 4 componenten al "Help Wanted", maar nog niet goed gemarkeerd in het Help Wanted bord. Die zijn nu bijgewerkt en met het updaten van Component Progress is nu de website zo ook 4 Help Wanted componenten rijker.
- Language Navigation
- Page Number Navigation
- Spinner
- Tabs

build: update component progress

---

docs/community/events/heartbeat/videos.mdx

feat: add heartbeat video 18 maart 2025 (#1264)

---

docs/componenten/ac/_ac_intro.md

Wijziging acceptatiecriteria introductie

---

.changeset/README.md

- Use <package> instead of a specific package
- Update the URL to point to the SemVer documentation

docs: update .changesets/README.md

---

packages/archimate/package.json

Had deze gemist toen provenance aanging

fix: archimate repository.url

---

.changeset/old-crabs-allow.md
docs/componenten/page-number-navigation/index.mdx

Description taken from Canvas: https://codefornl.slack.com/docs/T68FXPFQV/F07B9N5VDB3?focus_section_id=temp:C:TLI239a6485e8b343abb80a40b95

docs: add description of page number navigation component (#2178)

---

.changeset/baseline-2025-04.md
docs/baseline/2025-04.mdx

[Preview](https://documentatie-git-baseline-2025-04-nl-design-system.vercel.app/baseline/2025-04)
Closes [#2157](https://github.com/nl-design-system/documentatie/issues/2157)

baseline 2025-04

---

vercel.json

Make sure Vercel does not try to build the gh-pages branch in addition to the assets branch

fix: Vercel config

---

docs/handboek/designer/nieuwe-versie-publiceren/index.md

Add links to pages that have recently been published and are now publicly visible on the website.

chore: add links to index

---

package.json
pnpm-lock.yaml

De volgende componenten zijn nu Help Wanted
Een aantal ervan met de kanttekening dat deze mogelijk moeilijk helemaal toegankelijk te maken zijn en dan dus niet tot Hall of Fame komen.

chore: update component progress

---

.changeset/wcag-2.5.8-full-page.md
docs/wcag/2.5.08.mdx
docs/wcag/summaries/_2.5.8-summary.md

docs: wcag 2.5.8 full page

---

docs/richtlijnen/content/afbeeldingen/functionele-afbeeldingen.md

Met deze aanpassing wordt de begeleidende tekst gelijk aan de alt-tekst.

alt tekst gelijk met onderschrift

---

docs/community/events/heartbeat/videos.mdx

Heartbeat video van 29 april toegevoegd.

Heartbeat 29 april

---

.changeset/content-ondertiteling.md
docs/richtlijnen/content/video/README.mdx
docs/richtlijnen/content/video/_category_.json
docs/richtlijnen/content/video/ondertiteling.md

Nieuwe categorie in de richtlijnen Kennisbank: Video

docs: video richtlijnen voor ondertiteling

---

.changeset/wcag-3.3.7-full-page.md
docs/wcag/3.3.07.mdx
docs/wcag/summaries/_3.3.7-summary.md
src/css/custom.css

docs: wcag 3.3.7 full page

---

.changeset/box-of-chocolates.md
docs/richtlijnen/content/video/README.mdx

Overzichtspagina in content richtlijnen video aangevuld met introductie en verwijzingen naar wcag-richtlijnen pagina's.
closes #2313 
preview: https://documentatie-git-feat-kennisbankvideo-o-5fb0d8-nl-design-system.vercel.app/richtlijnen/content/video

Overzichtspagina video in content richtlijnen

---

.changeset/wcag-3.2.0-full-page.md
docs/wcag/3.2.06.mdx
docs/wcag/summaries/_3.2.6-summary.md

Docs/wcag 3.2.6 full

---

.changeset/wcag-3.3.8-full-page.md
docs/wcag/3.3.08.mdx
docs/wcag/summaries/_3.3.8-summary.md

fixes #681 
[Preview: WCAG-succescriterium 3.3.8 Toegankelijke authenticatie (minimum)](https://documentatie-git-docs-wcag-338-full-nl-design-system.vercel.app/wcag/3.3.8/#:R15ralaqh:)

docs: wcag 3.3.8 full page

---

.changeset/video-transcript.md
docs/richtlijnen/content/video/transcript.md

Pagina transcript bij video voor de content richtlijnen.
preview: https://documentatie-git-feat-kennisbankvideo-t-faefb0-nl-design-system.vercel.app/richtlijnen/content/video/transcript
closes #2318

Video transcript

---

.changeset/tall-poets-smile.md
docs/community/events/heartbeat/videos.mdx

Closes https://github.com/nl-design-system/kernteam/issues/1391

docs: heartbeat 13 mei 2025 (#1391)

---

.changeset/baseline-2025-05.md
docs/baseline/2025-05.mdx

baseline 2025 05

---

.changeset/video-stappenplan.md
docs/richtlijnen/content/video/README.mdx

Stappenplan voor het prioriteren van je toegankelijk te maken video's toegevoegd aan de video overzichtspagina.
preview: https://documentatie-git-feat-video-overzichtsp-359778-nl-design-system.vercel.app/richtlijnen/content/video 
closes #2342

Prioritering video's toegankelijk maken

---

docs/richtlijnen/content/tekstopmaak/emphasize-text.md
docs/richtlijnen/content/tekstopmaak/headings.md
docs/richtlijnen/content/tekstopmaak/link-text.md
docs/richtlijnen/content/tekstopmaak/quotes.md
docs/richtlijnen/content/tekstopmaak/summaries.md
docs/richtlijnen/content/tekstopmaak/tables.md

Plus wat verbeteringen in introductieteksten van verschillende pagina’s

Secties ‘hoe te testen’ toegevoegd aan de pagina's over tekstopmaak.

---

src/components/ComponentPage.tsx

Schrijffoutje "voortang" --> "voortgang"

fix: schrijffout component verbeteren

---

docs/community/community-sprints/overheidsbrede-portalen-community.mdx

GDH wordt al afgevangen door NL Portal in dit lijstje

docs: update overheidsbrede portalen community text

---

.changeset/wcag-3.2.3-full-page.md
docs/wcag/3.2.03.mdx
docs/wcag/summaries/_3.2.3-summary.md

Fixes #668 
Preview: https://documentatie-git-docs-wcag-323-full-nl-design-system.vercel.app/wcag/3.2.3

docs: wcag 3.2.3 full page

---

.changeset/givemeasign.md
docs/richtlijnen/content/video/gebarentaal.md

Contentrichtlijnen voor gebarentaal bij video
closes #2320 
preview: https://documentatie-git-feat-richtlijnen-video-9d7ef4-nl-design-system.vercel.app/richtlijnen/content/video/gebarentaal

Video richtlijnen Gebarentaal

---

.changeset/looking-rather-flashing.md
docs/richtlijnen/content/video/flitsen.md

Pagina over flitsen in video voor de contentrichtlijnen.
Closes #2321 
preview: https://documentatie-git-feat-richtlijnen-video-45feba-nl-design-system.vercel.app/richtlijnen/content/video/flitsen

Contenrichtlijnen video - Flitsen in video

---

.changeset/baseline-2025-06.md
docs/baseline/2024-12.mdx
docs/baseline/2025-04.mdx
docs/baseline/2025-05.mdx
docs/baseline/2025-06.mdx
docs/baseline/README.mdx

baseline 2025-06

---

.changeset/wcag-3.3.2-full-page.md
docs/wcag/3.3.02.mdx
docs/wcag/summaries/_3.3.2-summary.md

Fixes #671 
https://documentatie-git-docs-wcag-332-full-nl-design-system.vercel.app/wcag/3.3.2

docs: wcag 3.3.2 full page

---

.changeset/wcag-2.5.4-full-page.md
docs/wcag/2.5.04.mdx
docs/wcag/summaries/_2.5.4-summary.md

Fixes #663 
Preview: https://documentatie-git-docs-wcag-254-full-nl-design-system.vercel.app/

docs: wcag 2.5.4 full page

---

.changeset/stap-voor-stap.md
docs/handboek/designer/stappenplan.mdx

Hierbij de update van het Figma stappenplan. Nog niet helemaal compleet maar goed genoeg voor een review.
Preview: https://documentatie-git-docs-figma-stappenplan-nl-design-system.vercel.app/handboek/designer/stappenplan

docs: Figma stappenplan update

---

docs/handboek/estafettemodel.mdx
package.json
pnpm-lock.yaml
src/components/ComponentCard.css
src/components/ComponentCard.tsx
src/components/ComponentOverview.css
src/components/ComponentOverview.tsx
src/components/ComponentPage.css
src/components/ComponentPage.tsx
src/utils.ts

https://github.com/nl-design-system/kernteam/issues/1440

feat(ComponentOverview): add framework filter

---

package.json
pnpm-lock.yaml
src/components/ComponentPage.tsx

fix(ComponentPage): restore component progress

---

.changeset/figma-structuur-doc.md
docs/handboek/designer/werken-met-nl-design-system/figma-structuur.mdx

Documentatie voor Figma structuur bijgewerkt.

docs: documentatie voor Figma structuur

---

docs/handboek/designer/werken-met-nl-design-system/figma-migratie-stappenplan.mdx
docs/handboek/designer/werken-met-nl-design-system/figma-stappenplan.mdx

Link naar juiste Youtube gefixed.

Docs: fix video link

---

src/css/custom.css

- Added margin-bottom for ordered listst.
- Changed value form `px` to relative value `rem`

feat: add margin-bottom for ordered lists

---

docs/community/events/heartbeat/videos.mdx

We gaan niet alle oude Heartbeats ondertitelen.  We zetten er een paar 'uit' die men op aanvraag kan bekijken.

docs: remove private videos

---

docs/community/events/heartbeat/videos.mdx

Closes https://github.com/nl-design-system/kernteam/issues/1464

docs: add heartbeat 8 juli 2025

---

docs/handboek/component-bijdragen/community-stappenplan/voor-kernteam.mdx

- We spreken over Start-thema in plaats van Voorbeeld-thema.
- We spreken over Figma changelog in plaats van Bieb Sync video

docs: Community stappenplan voor kernteam bijgewerkt

---

docs/handboek/huisstijl-vastleggen/themas/themas.mdx

Link hersteld voor developers.

docs: link hersteld op thema pagina

---

.changeset/wcag-2.4.11-full-page.md
docs/wcag/2.4.11.mdx
docs/wcag/summaries/_2.4.11-summary.md

Fixes #676 
Preview: https://documentatie-git-docs-wcag-2411-full-nl-design-system.vercel.app/

docs: wcag 2.4.11 full page

---

src/theme/DocBreadcrumbs/index.tsx

Closes https://github.com/nl-design-system/documentatie/issues/2576

Fix voor breadcrumb links

---

.changeset/wcag-2.5.1-full-page.md
docs/wcag/2.5.01.mdx
docs/wcag/summaries/_2.5.1-summary.md

Fixes #660 
https://documentatie-git-docs-wcag-251-full-nl-design-system.vercel.app/wcag/2.5.1

docs: wcag 2.5.1 full page

---

static/overheidsbrede-portalen-community/overheidsbrede-portalen-community-afstemming.ics

Community liet weten dat dit tijdstip beter uitkomt, via @bddjong

docs: update overheidsbrede portalen community afstemming from 1300 to 1400

---

.changeset/wcag-2.2.1-full-page.md
docs/wcag/2.2.01.mdx
docs/wcag/summaries/_2.2.1-summary.md

Fixes #651
Preview: https://documentatie-git-docs-wcag-221-full-nl-design-system.vercel.app/wcag/2.2.1

docs: wcag 2.2.1 full page

---

.changeset/wicked-boxes-poke.md
docs/baseline/2025-07.mdx
docs/baseline/README.mdx

Fixes #2462
Preview: https://documentatie-git-baseline-2025-07-nl-design-system.vercel.app/baseline/2025-07/

baseline 2025-07

---

src/components/NewsletterSignUp.tsx

This reverts commit a36d0fc04eeed3355427d987159ca9ce5d04c731.

chore: revert fix: add max length

---

docs/handboek/designer/werken-met-nl-design-system/changelog-voor-figma.mdx
docs/handboek/designer/werken-met-nl-design-system/design-tokens-versiebeheer.mdx
docs/handboek/designer/werken-met-nl-design-system/figma-hygiene.mdx
docs/handboek/designer/werken-met-nl-design-system/figma-structuur.mdx
docs/handboek/designer/werken-met-nl-design-system/werken-met-nl-design-system.mdx
docs/handboek/designer/zelf-componenten-maken.mdx
docs/handboek/huisstijl-vastleggen/design-tokens.mdx
docs/handboek/huisstijl-vastleggen/themas/start-thema.mdx
docs/project/faq.mdx
docs/project/kernteam.mdx
docs/richtlijnen/_footer_info.md
docs/richtlijnen/formulieren/description/2-content/_guideline.md
docs/richtlijnen/stijl/README.mdx
docs/richtlijnen/stijl/colour/1-contrast-text/_guideline.md
docs/richtlijnen/stijl/icons/README.mdx
docs/richtlijnen/stijl/space/2-boxing-model/README.mdx
docs/richtlijnen/stijl/space/2-boxing-model/_guideline.md
docs/richtlijnen/stijl/space/3-spacing-concepts/README.mdx
docs/richtlijnen/stijl/space/3-spacing-concepts/_guideline.md
docs/wcag/2.4.13.mdx
docs/wcag/_wcag_footer_info.md
src/components/CoreTeam/Jeffrey.tsx

Enkele 'het-jes' verwijderd vooraf aan 'NL Design System'.

docs: het-jes verwijderen

---

.changeset/color-sparkly-new.md
docs/componenten/color-sample/index.mdx

Nieuwe opzet voor acceptatiecriteria voor de Color sample component.

Color sample component nieuwe opzet

---

.changeset/codeblock-sparkly-new.md
docs/componenten/ac/_wcag-1.3.1-code-block.md
docs/componenten/code-block/index.mdx

Nieuwe opzet voor acceptatiecriteria voor de Code block component.

Code block component nieuwe opzet

---

docs/handboek/designer/zelf-componenten-maken.mdx

Documentatie voor Zelf componenten maken voor designers herschreven en nieuwe video's toegevoegd.

docs: zelf componenten maken voor designers herschreven

---

docs/community/events/estafettemodeldag.mdx

As part of https://github.com/nl-design-system/kernteam/issues/1461

docs: herintroduceren estafettemodeldagen 2025

---

.changeset/paragraph-sparkly-new.md
docs/componenten/paragraph/index.mdx

Nieuwe opzet voor acceptatiecriteria voor de Paragraph component.

feat: paragraph nieuwe acceptatiecriteria opzet

---

docs/community/events/heartbeat/videos.mdx

Onderdeel van #1463
[Preview](https://documentatie-git-docs-add-heartbeat-19-6c224d-nl-design-system.vercel.app/events/heartbeat/videos/)

docs: add heartbeat 19 augustus 2025

---

.changeset/wcag-2.1.2-full-page.md
docs/wcag/2.1.02.mdx
docs/wcag/summaries/_2.1.2-summary.md

Fixes #649 
Preview: https://documentatie-git-docs-wcag-212-full-nl-design-system.vercel.app/wcag/2.1.2/

docs: wcag 2.1.2 full page

---

.changeset/ignore-the-voice.md
docs/componenten/ac/NLDS/_wcag-1.1.1-nlds-decorative-icon.md
docs/componenten/ac/_wcag-1.1.1-decorative-icon.md

Opmerking over VoiceOver toegevoegd aan de decoratieve icon snippets op de Icon componentpagina.
closes #2703

VoiceOver quirk toevoegen aan snippets decorative Icon documentatie

---

.changeset/describe-to-me.md
docs/wcag/1.1.01.mdx

Link naar richtlijnen voor afbeeldingen toegevoegd aan 1.1.1.
closes #2444

1.1.1 update

---

.changeset/cyan-berries-repair.md
docs/componenten/select-combobox/index.mdx
static/svg/componenten_overzicht_select-combobox.svg

Onderdeel van [Select combobox component door Help Wanted stappen halen](https://github.com/nl-design-system/kernteam/issues/948)
Preview: https://documentatie-git-feat-add-documentation-736306-nl-design-system.vercel.app/select-combobox/
Closes https://github.com/nl-design-system/kernteam/issues/948

feat: add documentation page for select combobox

---

docs/community/events/heartbeat/heartbeat.json
docs/community/events/heartbeat/videos.mdx

Voor https://github.com/nl-design-system/kernteam/issues/1538
Preview: https://documentatie-git-docs-add-heartbeat-16-2f3d98-nl-design-system.vercel.app/events/heartbeat/videos/

docs: add heartbeat 16 september 2025

---

.changeset/wcag-1.2.1-full-page.md
docs/wcag/1.2.01.mdx
docs/wcag/summaries/_1.2.1-summary.md

Fixes #630
Preview: https://documentatie-git-docs-wcag-121-full-nl-design-system.vercel.app/wcag/1.2.1

docs: wcag 1.2.1 full page

---

docs/community/belangenorganisaties/aanmelden-bedankt.mdx
docs/community/belangenorganisaties/aanmelden.mdx
sidebarConfig.ts
static/.htaccess

- [Aanmelden](https://documentatie-git-feat-inspraakrondes-nl-design-system.vercel.app/community/belangenorganisaties/aanmelden)
- [Bedankt voor je aanmelding](https://documentatie-git-feat-inspraakrondes-nl-design-system.vercel.app/community/belangenorganisaties/aanmelden-bedankt)

feat: aanmeldformulier belangenorganisaties

---

docs/handboek/developer/vercel.md

closes https://github.com/nl-design-system/documentatie/issues/2682

feat: add vercel documentation
